
<Process id="a582e771-644c-480b-91ed-ab2d6d40adeb" type="event" workType="foreground" name="E_Error" version="1.0" designerVersion="1.6.500.09031" isValid="true">
  <Properties>
    <Property key="Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="Os" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="Microsoft Windows 10 Pro64비트" />
    <Property key="Resolution" controlType="String" valueType="System.String" formatType="String_Size" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="1920x1080" />
    <Property key="RunningTime" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="11" />
    <Property key="Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="0" />
    <Property key="CreatedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2020-11-04 18:03:09" />
    <Property key="CreatedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastModifiedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2020-11-11 21:55:50" />
    <Property key="LastModifiedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" />
    <Property key="LastPublishedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" />
  </Properties>
  <LinkItems />
  <Variables>
    <Variable name="sender" scope="Input" valueType="Any" formatType="Any" initValue="this" desc="Task Object" />
    <Variable name="args" scope="Input" valueType="Any" formatType="Any" initValue="{message:'error message'}" desc="Exception Object" />
    <Variable name="senderName" scope="Normal" valueType="Any" formatType="Any" initValue="this.sender.constructor.name" desc="Task Name" />
    <Variable name="errorMessage" scope="Normal" valueType="Any" formatType="Any" initValue="Bot.GetProgressInfo(this.senderName) + '\n' + this.args.message" desc="Default Message Format" />
  </Variables>
  <Steps>
    <Step id="Sc558f5e9de304e0594e7ad90cb0038ab" ver="200825001" createVer="200825001" type="Flow" name="UntilLoop" apptitle="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="d2565c42-6e4c-416e-9092-4c19202cc809" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="Y" value="true" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="true" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S956742ad9b3c4863bb520d24fa97a03f" type="Flow" name="EndLoop" />
      </RelatedSteps>
      <Script><![CDATA[while (true) {]]></Script>
    </Step>
    <Step id="S9644f89a509c4614a8f1bbccac0952c1" ver="200825001" createVer="200825001" type="Desktop" name="MessageBox" apptitle="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="01ba8cee-a1f0-4012-ae8c-c9da0dc88f43" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Conditions_Arguments" controlType="Object" valueType="System.Object" formatType="Any" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'같은 시트가 존재합니다.\n1.종료 2.업데이트'" />
        <Property type="Desktop" key="Command_Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="4" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[MsgBox('같은 시트가 존재합니다.\n1.종료 2.업데이트', 4);]]></Script>
    </Step>
    <Step id="S5fe368969bc34aadae10a2c9f767460b" ver="200825001" createVer="200825001" type="Desktop" name="InputBox" apptitle="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="f27a20de-5719-4d19-a29d-80046a25a30b" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo" />
        <Property type="Desktop" key="Conditions_DefaultValue" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="''" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varChoiceOneTwo = InputBox('');]]></Script>
    </Step>
    <Step id="S0ee71425d3de4e36a8f591596e23b9f3" ver="200825001" createVer="200825001" type="Flow" name="Decision" apptitle="" tag="" depth="2" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="e5b6d27f-0467-4def-9834-5703f661a86d" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo == 1 || this.sender.varChoiceOneTwo == 2" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo == 1 || this.sender.varChoiceOneTwo == 2" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Saabc03784fae4807ac6c8de6ac7d8d27" type="Flow" name="Else" />
        <RelatedStep id="Sc2c462e67cb84684ba2fa0edc70677fa" type="Flow" name="EndDecision" />
      </RelatedSteps>
      <Script><![CDATA[if (this.sender.varChoiceOneTwo == 1 || this.sender.varChoiceOneTwo == 2) {]]></Script>
    </Step>
    <Step id="S3e3371607cf342f7815d2f498c9af1e7" ver="200825001" createVer="200825001" type="Flow" name="Break" apptitle="" tag="" depth="3" stmttype="Jump" enabled="True" mainSet="0">
      <Properties id="3dd8a9d7-be21-45c4-982b-f025a5e79c38" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[break;]]></Script>
    </Step>
    <Step id="Saabc03784fae4807ac6c8de6ac7d8d27" ver="200825001" createVer="200825001" type="Flow" name="Else" apptitle="" tag="" depth="3" stmttype="CloseOpenBlock" enabled="True" mainSet="0">
      <Properties id="d1c0228e-08fc-48a4-bd16-34a47b1760fc" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S0ee71425d3de4e36a8f591596e23b9f3" type="Flow" name="Decision" />
      </RelatedSteps>
      <Script><![CDATA[}else{]]></Script>
    </Step>
    <Step id="Sc2c462e67cb84684ba2fa0edc70677fa" ver="200825001" createVer="200825001" type="Flow" name="EndDecision" apptitle="" tag="" depth="3" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="a24917ef-05f5-40c8-b326-9b0f7dde2f76" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S0ee71425d3de4e36a8f591596e23b9f3" type="Flow" name="Decision" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S956742ad9b3c4863bb520d24fa97a03f" ver="200825001" createVer="200825001" type="Flow" name="EndLoop" apptitle="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="a111c4b9-c9b6-4dea-af3f-184c4bfef2fc" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sc558f5e9de304e0594e7ad90cb0038ab" type="Flow" name="UntilLoop" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S79063850a97846dcb1f78e91041a6642" ver="200825001" createVer="200825001" type="Flow" name="DecisionThen" apptitle="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="72cc983d-95ce-499e-bbe3-a388d40069d4" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo == 1" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo == 1" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S5fde29d2532f4acd80fda93e12cfd2d3" type="Flow" name="EndDecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[if (this.sender.varChoiceOneTwo == 1) {]]></Script>
    </Step>
    <Step id="Scb9cfb5756ad4eb5aaaf9efb9eb944dd" ver="200825001" createVer="200825001" type="Excel" name="CloseExcel" apptitle="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="0345ef82-e938-451a-a254-f52cdb6c37e9" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="File_Force" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.CloseExcel(this.closeexcel_info_10);]]></Script>
    </Step>
    <Step id="S5890c4b49e0648d48877c27dea8a10b0" ver="200825001" createVer="200825001" type="Desktop" name="DeleteFile" apptitle="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="cc8ab809-6f23-418e-b22c-7daa69103c3d" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Command_Path" controlType="File" valueType="System.String" formatType="String_FilePath" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'C:\\Temp\\데이터excel.xls'" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[SystemLib.DeleteFile('C:\\Temp\\데이터excel.xls');]]></Script>
    </Step>
    <Step id="Sa664d94402db42a0a08c36db90ce3981" ver="200825001" createVer="200825001" type="Flow" name="TerminateAll" apptitle="" tag="" depth="2" stmttype="Jump" enabled="True" mainSet="0">
      <Properties id="ddc4c861-6ea8-404d-8d5e-a3a0cbc6f137" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_ExitType" controlType="PropertyItemToggleExView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="Stop" toggle="Pass;Fail;Stop" order="1" />
        <Property type="Flow" key="Conditions_ExitCode" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Result" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Exit('Stop', null, null);]]></Script>
    </Step>
    <Step id="S5fde29d2532f4acd80fda93e12cfd2d3" ver="200825001" createVer="200825001" type="Flow" name="EndDecisionThen" apptitle="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="43428b53-a45d-4436-9d35-3c76b66075cd" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S79063850a97846dcb1f78e91041a6642" type="Flow" name="DecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="Se1b588f2bc66455f9e487e5584d9b5c6" ver="200825001" createVer="200825001" type="Flow" name="DecisionThen" apptitle="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="72cc983d-95ce-499e-bbe3-a388d40069d4" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo == 2" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo == 2" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S4fb2f2ae6ace472c81421615e546c80b" type="Flow" name="EndDecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[if (this.sender.varChoiceOneTwo == 2) {]]></Script>
    </Step>
    <Step id="S3d5c0b92b79247e1a1a8834f57e05746" ver="200825001" createVer="200825001" type="Flow" name="Block" apptitle="" tag="" depth="2" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="44739690-7ce3-4d76-9eef-8a425d9690c1" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Title" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="' 업데이트 입력'" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sa2785a31d51c4acb93fe93bddbc8c484" type="Flow" name="EndBlock" />
      </RelatedSteps>
      <Script><![CDATA[{]]></Script>
    </Step>
    <Step id="S4054ba557fa145428b8db42cae203af6" ver="200825001" createVer="200825001" type="Excel" name="DeleteWorkSheet" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="d6856038-89f2-4957-9885-03c64ee6e9b9" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSheetBoolean" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.DeleteWorkSheet(this.deleteworksheet_info_16);]]></Script>
    </Step>
    <Step id="Sfc6ef0b5be114e95b3f10c70cda6625e" ver="200825001" createVer="200825001" type="Excel" name="GetSheetName" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="53d87f2d-4c90-41ec-8399-72e04c3570c8" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="Output_SheetName" controlType="OutputControlType" valueType="System.String" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varTryExpBoolean" />
        <Property type="Excel" key="Sheet_Position" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="1" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varTryExpBoolean = Excel.GetSheetName(this.getsheetname_info_17);]]></Script>
    </Step>
    <Step id="Sf2320cc0df9341fb8d559083275da7cc" ver="200825001" createVer="200825001" type="Excel" name="CopyWorkSheet" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="ba16f69d-1a63-483b-82d5-7761fdb10d69" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="--Ignore--" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="File_SourceSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'draft'" />
        <Property type="Excel" key="File_TargetSheet" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftSheetName" />
        <Property type="Excel" key="File_BeforeSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varTryExpBoolean" />
        <Property type="Excel" key="File_AfterSheet" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[try{
    Excel.CopyWorkSheet(this.copyworksheet_info_18);
}catch(e){
    Warn('CatchException: ' + e.message);
}
]]></Script>
    </Step>
    <Step id="S39ec88569c194f82be06d71f599e7388" ver="200825001" createVer="200825001" type="Excel" name="CopyPaste" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="f56c084b-eb69-4f04-812b-06d8f26b7e44" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="File_SourceExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="File_SourceSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소(전체)'" />
        <Property type="Excel" key="File_SourceRange" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'A5:'+this.sender.varRowCount[0]" />
        <Property type="Excel" key="File_TargetExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="File_TargetSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftSheetName" />
        <Property type="Excel" key="File_TargetRange" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'A5:'+this.sender.varRowCount[0]" />
        <Property type="Excel" key="File_TargetAutoSave" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="All" valuelist="All;UsingSourceTheme;Formulas;ExceptBorders;Values;ColumnWidths;Formats;FormulasAndNumberFormats;Comments;ValuesAndNumberFormats;Validation;MergingConditionalFormats" />
        <Property type="Excel" key="Input_PasteOperation" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="None" valuelist="None;Add;Subtract;Multiply;Divide" />
        <Property type="Excel" key="Input_PasteSkipBlanks" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteTranspose" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteUseLink" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.CopyPaste(this.copypaste_info_19);]]></Script>
    </Step>
    <Step id="S7d9689afcaaa4c09ac2357b07c531225" ver="200825001" createVer="200825001" type="Excel" name="CopyPaste" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="f56c084b-eb69-4f04-812b-06d8f26b7e44" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="File_SourceExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="File_SourceSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소(전체)'" />
        <Property type="Excel" key="File_SourceRange" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'J2:'+this.sender.varRowCount[1]" />
        <Property type="Excel" key="File_TargetExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="File_TargetSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftSheetName" />
        <Property type="Excel" key="File_TargetRange" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'H5:'+this.sender.varRowCount[2]" />
        <Property type="Excel" key="File_TargetAutoSave" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="All" valuelist="All;UsingSourceTheme;Formulas;ExceptBorders;Values;ColumnWidths;Formats;FormulasAndNumberFormats;Comments;ValuesAndNumberFormats;Validation;MergingConditionalFormats" />
        <Property type="Excel" key="Input_PasteOperation" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="None" valuelist="None;Add;Subtract;Multiply;Divide" />
        <Property type="Excel" key="Input_PasteSkipBlanks" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteTranspose" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteUseLink" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.CopyPaste(this.copypaste_info_20);]]></Script>
    </Step>
    <Step id="Saece4dde5078430da9aa3d106400b11c" ver="200825001" createVer="200825001" type="Flow" name="SwitchGroup" apptitle="" tag="" depth="3" stmttype="OpenSwichBlock" enabled="True" mainSet="0">
      <Properties id="e22a470c-8c12-4ac5-86e4-6d73f75b83d5" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Condition" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varDay" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[switch (this.sender.varDay) {]]></Script>
    </Step>
    <Step id="S777eda81e7304a51aae43a96ea19d03f" ver="200825001" createVer="200825001" type="Flow" name="SwitchCase" apptitle="" tag="" depth="4" stmttype="OpenSwichBlock" enabled="True" mainSet="0">
      <Properties id="e8dda7e6-162f-4b5b-9056-1b40f856d213" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Case" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="6" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sadbd426e63bf4ca3b36e19c6daa75247" type="Flow" name="EndSwitchCase" />
      </RelatedSteps>
      <Script><![CDATA[case 6:{ ]]></Script>
    </Step>
    <Step id="Scaea3b4474194d89b380b97e6143f93b" ver="200825001" createVer="200825001" type="Flow" name="Loop" apptitle="" tag="" depth="5" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="7d4d8164-4128-4f7a-8b5b-713d6d79691b" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_InitializeIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i = 2" />
        <Property type="Flow" key="Conditions_LoopCondition" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i &lt;=this.sender.outTotalRow" />
        <Property type="Flow" key="Conditions_UpdateIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.i++" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Scb8ca04cbb304c279a7d94033931551e" type="Flow" name="EndLoop" />
      </RelatedSteps>
      <Script><![CDATA[for (this.i = 2; this.i <=this.sender.outTotalRow; this.i++) {]]></Script>
    </Step>
    <Step id="S040e4f7b8af14ff197d6722b24122833" ver="200825001" createVer="200825001" type="Excel" name="ReadRange" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="48d3fd40-ddd4-442f-8dc8-9152e8776905" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="Output_DataArray" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varDayArray[1]" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소(전체)'" />
        <Property type="Excel" key="Sheet_Range" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'H'+this.i" />
        <Property type="Excel" key="Input_ReadCellType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="Data" valuelist="Data;Value;Formula;Text" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varDayArray[1] = Excel.ReadRange(this.readrange_info_24);]]></Script>
    </Step>
    <Step id="Seec20521216e495c86fa7f60a13ba3a9" ver="200825001" createVer="200825001" type="Flow" name="Assign" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="ebfe84db-a474-493c-baa6-42fe135b4483" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.verTimeboolean" />
        <Property type="Flow" key="Conditions_Value" controlType="PropertyItemTextView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="&quot;평일 : &quot;+this.sender.varDayArray[1]" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.verTimeboolean = "평일 : "+this.sender.varDayArray[1];]]></Script>
    </Step>
    <Step id="S2c92d794d5f541499a3ac96c66920c02" ver="200825001" createVer="200825001" type="Flow" name="Assign" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="a36ef1dc-7c78-4ada-998f-25148a401c5a" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varthisIPlus" />
        <Property type="Flow" key="Conditions_Value" controlType="PropertyItemTextView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i+3" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varthisIPlus = this.i+3;]]></Script>
    </Step>
    <Step id="S0748c54643614290a021bdd846f1f2d1" ver="200825001" createVer="200825001" type="Excel" name="WriteRange" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="daf21c32-048a-45c0-8c92-961f1ee32956" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="Input_DataArray" controlType="Object[][]" valueType="System.Object[][]" formatType="Array2D" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.verTimeboolean" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftSheetName" />
        <Property type="Excel" key="Sheet_StartCell" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'G'+this.sender.varthisIPlus" />
        <Property type="Excel" key="File_AutoSave" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.WriteRange(this.writerange_info_27);]]></Script>
    </Step>
    <Step id="Scb8ca04cbb304c279a7d94033931551e" ver="200825001" createVer="200825001" type="Flow" name="EndLoop" apptitle="" tag="" depth="6" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="4a9e4fdb-711d-4d72-b5e6-516ef2b26af1" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Scaea3b4474194d89b380b97e6143f93b" type="Flow" name="Loop" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="Sadbd426e63bf4ca3b36e19c6daa75247" ver="200825001" createVer="200825001" type="Flow" name="EndSwitchCase" apptitle="" tag="" depth="5" stmttype="CloseSwichBlock" enabled="True" mainSet="0">
      <Properties id="b5550acf-c438-48fc-8264-55fdb12bb2d1" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S777eda81e7304a51aae43a96ea19d03f" type="Flow" name="SwitchCase" />
      </RelatedSteps>
      <Script><![CDATA[break;
}]]></Script>
    </Step>
    <Step id="Sae28c2336462418c838bfe3e331bfc23" ver="200825001" createVer="200825001" type="Flow" name="SwitchCase" apptitle="" tag="" depth="4" stmttype="OpenSwichBlock" enabled="True" mainSet="0">
      <Properties id="71380a31-ee4a-4144-8b53-3f47e06bb330" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Case" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="0" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S6a5e12b918e54ec0b9604805ef2f4a97" type="Flow" name="EndSwitchCase" />
      </RelatedSteps>
      <Script><![CDATA[case 0:{ ]]></Script>
    </Step>
    <Step id="Saac371b706274cdbbceda9d06e582b3f" ver="200825001" createVer="200825001" type="Flow" name="Loop" apptitle="" tag="" depth="5" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="7d4d8164-4128-4f7a-8b5b-713d6d79691b" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_InitializeIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i = 2" />
        <Property type="Flow" key="Conditions_LoopCondition" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i &lt;=this.sneder.outTotalRow" />
        <Property type="Flow" key="Conditions_UpdateIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.i++" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S592ce27c6a724646ab71fae606c68982" type="Flow" name="EndLoop" />
      </RelatedSteps>
      <Script><![CDATA[for (this.i = 2; this.i <=this.sneder.outTotalRow; this.i++) {]]></Script>
    </Step>
    <Step id="S9d0c6a31d29f4b41bd4130c1db52b90c" ver="200825001" createVer="200825001" type="Excel" name="ReadRange" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="48d3fd40-ddd4-442f-8dc8-9152e8776905" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="Output_DataArray" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varDayArray[2]" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소(전체)'" />
        <Property type="Excel" key="Sheet_Range" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'I'+this.i" />
        <Property type="Excel" key="Input_ReadCellType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="Data" valuelist="Data;Value;Formula;Text" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varDayArray[2] = Excel.ReadRange(this.readrange_info_32);]]></Script>
    </Step>
    <Step id="S08f5176498994de5b5f857dabfe6050e" ver="200825001" createVer="200825001" type="Flow" name="Assign" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="ebfe84db-a474-493c-baa6-42fe135b4483" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.verTimeboolean" />
        <Property type="Flow" key="Conditions_Value" controlType="PropertyItemTextView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="&quot;평일 : &quot;+this.sender.varDayArray[2]" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.verTimeboolean = "평일 : "+this.sender.varDayArray[2];]]></Script>
    </Step>
    <Step id="S304b00d630904cf3ba81927ee30a2522" ver="200825001" createVer="200825001" type="Flow" name="Assign" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="a36ef1dc-7c78-4ada-998f-25148a401c5a" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varthisIPlus" />
        <Property type="Flow" key="Conditions_Value" controlType="PropertyItemTextView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i+3" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varthisIPlus = this.i+3;]]></Script>
    </Step>
    <Step id="S6767dcb32faf40d1b5c0f2db6cbdb769" ver="200825001" createVer="200825001" type="Excel" name="WriteRange" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="daf21c32-048a-45c0-8c92-961f1ee32956" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="Input_DataArray" controlType="Object[][]" valueType="System.Object[][]" formatType="Array2D" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.verTimeboolean" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftSheetName" />
        <Property type="Excel" key="Sheet_StartCell" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'G'+this.sender.varthisIPlus" />
        <Property type="Excel" key="File_AutoSave" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.WriteRange(this.writerange_info_35);]]></Script>
    </Step>
    <Step id="S592ce27c6a724646ab71fae606c68982" ver="200825001" createVer="200825001" type="Flow" name="EndLoop" apptitle="" tag="" depth="6" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="4a9e4fdb-711d-4d72-b5e6-516ef2b26af1" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Saac371b706274cdbbceda9d06e582b3f" type="Flow" name="Loop" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S6a5e12b918e54ec0b9604805ef2f4a97" ver="200825001" createVer="200825001" type="Flow" name="EndSwitchCase" apptitle="" tag="" depth="5" stmttype="CloseSwichBlock" enabled="True" mainSet="0">
      <Properties id="50029a15-560c-4c68-9d4a-896869ae4579" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sae28c2336462418c838bfe3e331bfc23" type="Flow" name="SwitchCase" />
      </RelatedSteps>
      <Script><![CDATA[break;
}]]></Script>
    </Step>
    <Step id="S8328e1a557444bee9d565a2325c17d86" ver="200825001" createVer="200825001" type="Flow" name="SwitchDefault" apptitle="" tag="" depth="4" stmttype="OpenSwichBlock" enabled="True" mainSet="0">
      <Properties id="d3ce7768-4203-4f34-bcc1-060f2dc60db4" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S02591937889a4e5aa1cbf73f86a615e8" type="Flow" name="EndSwitchDefault" />
      </RelatedSteps>
      <Script><![CDATA[default:{ ]]></Script>
    </Step>
    <Step id="S1b2253407fba43ea8ff61840e41277b1" ver="200825001" createVer="200825001" type="Flow" name="Loop" apptitle="" tag="" depth="5" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="7d4d8164-4128-4f7a-8b5b-713d6d79691b" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_InitializeIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i = 2" />
        <Property type="Flow" key="Conditions_LoopCondition" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i &lt;=this.sender.outTotalRow" />
        <Property type="Flow" key="Conditions_UpdateIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.i++" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sda5120e40f074c1fa37075c0cfa022cd" type="Flow" name="EndLoop" />
      </RelatedSteps>
      <Script><![CDATA[for (this.i = 2; this.i <=this.sender.outTotalRow; this.i++) {]]></Script>
    </Step>
    <Step id="S50c0ae8a94f04d438d2627bcf581e45b" ver="200825001" createVer="200825001" type="Excel" name="ReadRange" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="48d3fd40-ddd4-442f-8dc8-9152e8776905" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="Output_DataArray" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varDayArray[0]" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소(전체)'" />
        <Property type="Excel" key="Sheet_Range" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'G'+this.i" />
        <Property type="Excel" key="Input_ReadCellType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="Data" valuelist="Data;Value;Formula;Text" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varDayArray[0] = Excel.ReadRange(this.readrange_info_40);]]></Script>
    </Step>
    <Step id="Se22b245446d646a3a699705792630136" ver="200825001" createVer="200825001" type="Flow" name="Assign" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="ebfe84db-a474-493c-baa6-42fe135b4483" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.verTimeboolean" />
        <Property type="Flow" key="Conditions_Value" controlType="PropertyItemTextView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="&quot;평일 : &quot;+this.sender.varDayArray[0]" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.verTimeboolean = "평일 : "+this.sender.varDayArray[0];]]></Script>
    </Step>
    <Step id="S328cdb2bc62e4c97ad912fc38afd9f65" ver="200825001" createVer="200825001" type="Flow" name="Assign" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="a36ef1dc-7c78-4ada-998f-25148a401c5a" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varthisIPlus" />
        <Property type="Flow" key="Conditions_Value" controlType="PropertyItemTextView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i+3" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varthisIPlus = this.i+3;]]></Script>
    </Step>
    <Step id="Se2c93c70a4144358bb2182f78fce9b74" ver="200825001" createVer="200825001" type="Excel" name="WriteRange" apptitle="" tag="" depth="6" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="daf21c32-048a-45c0-8c92-961f1ee32956" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="Input_DataArray" controlType="Object[][]" valueType="System.Object[][]" formatType="Array2D" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.verTimeboolean" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftSheetName" />
        <Property type="Excel" key="Sheet_StartCell" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'G'+this.sender.varthisIPlus" />
        <Property type="Excel" key="File_AutoSave" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.WriteRange(this.writerange_info_43);]]></Script>
    </Step>
    <Step id="Sda5120e40f074c1fa37075c0cfa022cd" ver="200825001" createVer="200825001" type="Flow" name="EndLoop" apptitle="" tag="" depth="6" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="4a9e4fdb-711d-4d72-b5e6-516ef2b26af1" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S1b2253407fba43ea8ff61840e41277b1" type="Flow" name="Loop" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S02591937889a4e5aa1cbf73f86a615e8" ver="200825001" createVer="200825001" type="Flow" name="EndSwitchDefault" apptitle="" tag="" depth="5" stmttype="CloseSwichBlock" enabled="True" mainSet="0">
      <Properties id="a1840834-4a00-4ace-819d-341ddcb6bc50" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S8328e1a557444bee9d565a2325c17d86" type="Flow" name="SwitchDefault" />
      </RelatedSteps>
      <Script><![CDATA[break;
}]]></Script>
    </Step>
    <Step id="Sa2785a31d51c4acb93fe93bddbc8c484" ver="200825001" createVer="200825001" type="Flow" name="EndBlock" apptitle="" tag="" depth="3" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="3f829443-48cf-4095-86de-fcd99d8664c0" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S3d5c0b92b79247e1a1a8834f57e05746" type="Flow" name="Block" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S4fb2f2ae6ace472c81421615e546c80b" ver="200825001" createVer="200825001" type="Flow" name="EndDecisionThen" apptitle="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="43428b53-a45d-4436-9d35-3c76b66075cd" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Se1b588f2bc66455f9e487e5584d9b5c6" type="Flow" name="DecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
  </Steps>
  <JScript><![CDATA[function E_Error(args) {

    this.sender = (typeof args != 'undefined') ? args.sender : this;
    this.args = (typeof args != 'undefined') ? args.args : {message:'error message'};
    this.senderName = this.sender.constructor.name;
    this.errorMessage = Bot.GetProgressInfo(this.senderName) + '\n' + this.args.message;

    this.run = function() {

        //------------------------------------------------
        STEP('Sc558f5e9de304e0594e7ad90cb0038ab', '[1] While');
        while (true) {

            //------------------------------------------------
            STEP('S9644f89a509c4614a8f1bbccac0952c1', '[2] MessageBox');
            MsgBox('같은 시트가 존재합니다.\n1.종료 2.업데이트', 4);

            //------------------------------------------------
            STEP('S5fe368969bc34aadae10a2c9f767460b', '[3] InputBox');
            this.sender.varChoiceOneTwo = InputBox('');

            //------------------------------------------------
            STEP('S0ee71425d3de4e36a8f591596e23b9f3', '[4] If');
            if (this.sender.varChoiceOneTwo == 1 || this.sender.varChoiceOneTwo == 2) {

                //------------------------------------------------
                STEP('S3e3371607cf342f7815d2f498c9af1e7', '[5] Break');
                break;

            //------------------------------------------------
            }else{
                STEP('Saabc03784fae4807ac6c8de6ac7d8d27', '[6] Else');

            //------------------------------------------------
            }
            STEP('Sc2c462e67cb84684ba2fa0edc70677fa', '[7] End-If');

        //------------------------------------------------
        }
        STEP('S956742ad9b3c4863bb520d24fa97a03f', '[8] End-While');

        //------------------------------------------------
        STEP('S79063850a97846dcb1f78e91041a6642', '[9] IfThen');
        if (this.sender.varChoiceOneTwo == 1) {

            //------------------------------------------------
            STEP('Scb9cfb5756ad4eb5aaaf9efb9eb944dd', '[10] CloseExcel');
            Excel.CloseExcel(this.closeexcel_info_10);

            //------------------------------------------------
            STEP('S5890c4b49e0648d48877c27dea8a10b0', '[11] DeleteFile');
            SystemLib.DeleteFile('C:\\Temp\\데이터excel.xls');

            //------------------------------------------------
            STEP('Sa664d94402db42a0a08c36db90ce3981', '[12] TerminateAll');
            Exit('Stop', null, null);

        //------------------------------------------------
        }
        STEP('S5fde29d2532f4acd80fda93e12cfd2d3', '[13] End-IfThen');

        //------------------------------------------------
        STEP('Se1b588f2bc66455f9e487e5584d9b5c6', '[14] IfThen');
        if (this.sender.varChoiceOneTwo == 2) {

            //------------------------------------------------
            STEP('S3d5c0b92b79247e1a1a8834f57e05746', '[15] Block');
            {

                //------------------------------------------------
                STEP('S4054ba557fa145428b8db42cae203af6', '[16] DeleteWorkSheet');
                Excel.DeleteWorkSheet(this.deleteworksheet_info_16);

                //------------------------------------------------
                STEP('Sfc6ef0b5be114e95b3f10c70cda6625e', '[17] GetSheetName');
                this.sender.varTryExpBoolean = Excel.GetSheetName(this.getsheetname_info_17);

                //------------------------------------------------
                STEP('Sf2320cc0df9341fb8d559083275da7cc', '[18] CopyWorkSheet');
                try{
                    Excel.CopyWorkSheet(this.copyworksheet_info_18);
                }catch(e){
                    Warn('CatchException: ' + e.message);
                }


                //------------------------------------------------
                STEP('S39ec88569c194f82be06d71f599e7388', '[19] CopyPaste');
                Excel.CopyPaste(this.copypaste_info_19);

                //------------------------------------------------
                STEP('S7d9689afcaaa4c09ac2357b07c531225', '[20] CopyPaste');
                Excel.CopyPaste(this.copypaste_info_20);

                //------------------------------------------------
                STEP('Saece4dde5078430da9aa3d106400b11c', '[21] SwitchGroup');
                switch (this.sender.varDay) {

                    //------------------------------------------------
                    case 6:{ 
                    STEP('S777eda81e7304a51aae43a96ea19d03f', '[22] SwitchCase');

                        //------------------------------------------------
                        STEP('Scaea3b4474194d89b380b97e6143f93b', '[23] For');
                        for (this.i = 2; this.i <=this.sender.outTotalRow; this.i++) {

                            //------------------------------------------------
                            STEP('S040e4f7b8af14ff197d6722b24122833', '[24] ReadRange');
                            this.sender.varDayArray[1] = Excel.ReadRange(this.readrange_info_24);

                            //------------------------------------------------
                            STEP('Seec20521216e495c86fa7f60a13ba3a9', '[25] Assign');
                            this.sender.verTimeboolean = "평일 : "+this.sender.varDayArray[1];

                            //------------------------------------------------
                            STEP('S2c92d794d5f541499a3ac96c66920c02', '[26] Assign');
                            this.sender.varthisIPlus = this.i+3;

                            //------------------------------------------------
                            STEP('S0748c54643614290a021bdd846f1f2d1', '[27] WriteRange');
                            Excel.WriteRange(this.writerange_info_27);

                        //------------------------------------------------
                        }
                        STEP('Scb8ca04cbb304c279a7d94033931551e', '[28] End-For');

                    //------------------------------------------------
                    STEP('Sadbd426e63bf4ca3b36e19c6daa75247', '[29] EndSwitchCase');
                    break;
                    }

                    //------------------------------------------------
                    case 0:{ 
                    STEP('Sae28c2336462418c838bfe3e331bfc23', '[30] SwitchCase');

                        //------------------------------------------------
                        STEP('Saac371b706274cdbbceda9d06e582b3f', '[31] For');
                        for (this.i = 2; this.i <=this.sneder.outTotalRow; this.i++) {

                            //------------------------------------------------
                            STEP('S9d0c6a31d29f4b41bd4130c1db52b90c', '[32] ReadRange');
                            this.sender.varDayArray[2] = Excel.ReadRange(this.readrange_info_32);

                            //------------------------------------------------
                            STEP('S08f5176498994de5b5f857dabfe6050e', '[33] Assign');
                            this.sender.verTimeboolean = "평일 : "+this.sender.varDayArray[2];

                            //------------------------------------------------
                            STEP('S304b00d630904cf3ba81927ee30a2522', '[34] Assign');
                            this.sender.varthisIPlus = this.i+3;

                            //------------------------------------------------
                            STEP('S6767dcb32faf40d1b5c0f2db6cbdb769', '[35] WriteRange');
                            Excel.WriteRange(this.writerange_info_35);

                        //------------------------------------------------
                        }
                        STEP('S592ce27c6a724646ab71fae606c68982', '[36] End-For');

                    //------------------------------------------------
                    STEP('S6a5e12b918e54ec0b9604805ef2f4a97', '[37] EndSwitchCase');
                    break;
                    }

                    //------------------------------------------------
                    default:{ 
                    STEP('S8328e1a557444bee9d565a2325c17d86', '[38] SwitchDefault');

                        //------------------------------------------------
                        STEP('S1b2253407fba43ea8ff61840e41277b1', '[39] For');
                        for (this.i = 2; this.i <=this.sender.outTotalRow; this.i++) {

                            //------------------------------------------------
                            STEP('S50c0ae8a94f04d438d2627bcf581e45b', '[40] ReadRange');
                            this.sender.varDayArray[0] = Excel.ReadRange(this.readrange_info_40);

                            //------------------------------------------------
                            STEP('Se22b245446d646a3a699705792630136', '[41] Assign');
                            this.sender.verTimeboolean = "평일 : "+this.sender.varDayArray[0];

                            //------------------------------------------------
                            STEP('S328cdb2bc62e4c97ad912fc38afd9f65', '[42] Assign');
                            this.sender.varthisIPlus = this.i+3;

                            //------------------------------------------------
                            STEP('Se2c93c70a4144358bb2182f78fce9b74', '[43] WriteRange');
                            Excel.WriteRange(this.writerange_info_43);

                        //------------------------------------------------
                        }
                        STEP('Sda5120e40f074c1fa37075c0cfa022cd', '[44] End-For');

                    //------------------------------------------------
                    STEP('S02591937889a4e5aa1cbf73f86a615e8', '[45] EndSwitchDefault');
                    break;
                    }

                }

            //------------------------------------------------
            }
            STEP('Sa2785a31d51c4acb93fe93bddbc8c484', '[46] End-Block');

        //------------------------------------------------
        }
        STEP('S4fb2f2ae6ace472c81421615e546c80b', '[47] End-IfThen');


    }

    this.execute = function() {
        var result = null;
        result = this.run()
        if (result != null)
            return result;
    }
}
]]></JScript>
  <Diagram version="1.200" layout="Horizontal" nodesize="Normal">
    <Nodes>
      <Node id="0" step_id="" container_id="" order="" type="StartNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="START" bounds="30,54,56,56" />
      <Node id="1" step_id="" container_id="" order="" type="EndNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="END" bounds="2632,266,56,56" />
      <Node id="2" step_id="df0f4fc5-7724-40a8-898b-dbb0049efb29" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="222,30,220,104" />
      <Node id="3" step_id="S9644f89a509c4614a8f1bbccac0952c1" container_id="2" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="MessageBox" bounds="228,54,208,74" />
      <Node id="4" step_id="723c1c4c-874b-467f-a2ec-fd1495e16bdd" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="472,30,220,104" />
      <Node id="5" step_id="S5fe368969bc34aadae10a2c9f767460b" container_id="4" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="InputBox" bounds="478,54,208,74" />
      <Node id="6" step_id="S0ee71425d3de4e36a8f591596e23b9f3" container_id="" order="" type="DecisionNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="722,54,76,56" />
      <Node id="7" step_id="a1b6ff49-bfaa-4ab8-94c3-1786a4055666" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="828,30,220,104" />
      <Node id="8" step_id="S3e3371607cf342f7815d2f498c9af1e7" container_id="7" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Break" bounds="834,54,208,74" />
      <Node id="9" step_id="Sc2c462e67cb84684ba2fa0edc70677fa" container_id="" order="" type="EndDecisionNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="722,266,76,56" />
      <Node id="10" step_id="Se1b588f2bc66455f9e487e5584d9b5c6" container_id="" order="" type="DecisionThenNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="1540,266,76,56" />
      <Node id="11" step_id="S3d5c0b92b79247e1a1a8834f57e05746" container_id="" order="" type="BlockNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="1646,257.5,35,73" />
      <Node id="12" step_id="557db5d4-2335-42e0-a1b4-7b007e89a0b0" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="1711,164,220,260" />
      <Node id="13" step_id="S4054ba557fa145428b8db42cae203af6" container_id="12" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="DeleteWorkSheet" bounds="1717,188,208,74" />
      <Node id="14" step_id="2767d9db-c2ea-403c-9b59-72b95a059043" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="1961,203,220,182" />
      <Node id="15" step_id="S39ec88569c194f82be06d71f599e7388" container_id="14" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="CopyPaste" bounds="1967,227,208,74" />
      <Node id="16" step_id="S7d9689afcaaa4c09ac2357b07c531225" container_id="14" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="CopyPaste" bounds="1967,305,208,74" />
      <Node id="17" step_id="Sa2785a31d51c4acb93fe93bddbc8c484" container_id="" order="" type="EndBlockNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="2461,257.5,35,73" />
      <Node id="18" step_id="S4fb2f2ae6ace472c81421615e546c80b" container_id="" order="" type="EndDecisionThenNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="2526,266,76,56" />
      <Node id="19" step_id="Saece4dde5078430da9aa3d106400b11c" container_id="" order="" type="SwitchGroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="True" expanded="True" text="this.sender.varDay" bounds="2211,185.5,220,217" />
      <Node id="20" step_id="S777eda81e7304a51aae43a96ea19d03f" container_id="27" order="" type="SwitchCaseNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="4422,666.999999999998,56,56" />
      <Node id="21" step_id="Scaea3b4474194d89b380b97e6143f93b" container_id="27" order="" type="LoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="4508,666.999999999997,76,56" />
      <Node id="22" step_id="00181e36-05a1-4ff8-b349-297f73adc5f8" container_id="27" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="4614,525.999999999997,220,338" />
      <Node id="23" step_id="S040e4f7b8af14ff197d6722b24122833" container_id="22" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="ReadRange" bounds="4620,549.999999999997,208,74" />
      <Node id="24" step_id="S0748c54643614290a021bdd846f1f2d1" container_id="22" order="3" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="WriteRange" bounds="4620,783.999999999997,208,74" />
      <Node id="25" step_id="Scb8ca04cbb304c279a7d94033931551e" container_id="27" order="" type="EndLoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="4864,666.999999999996,76,56" />
      <Node id="26" step_id="Sadbd426e63bf4ca3b36e19c6daa75247" container_id="27" order="" type="EndSwitchCaseNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="4970,667.000000000001,56,56" />
      <Node id="27" step_id="" container_id="19" order="0" type="FlowControlGroupNode" invoke_type="" flowcontrol_type="SwitchCase" flowcontrol_enabled="True" expanded="" text="" desc="6" bounds="2217,234.499999999999,208,54" />
      <Node id="28" step_id="Sae28c2336462418c838bfe3e331bfc23" container_id="35" order="" type="SwitchCaseNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="4422,666.999999999999,56,56" />
      <Node id="29" step_id="Saac371b706274cdbbceda9d06e582b3f" container_id="35" order="" type="LoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="4508,666.999999999999,76,56" />
      <Node id="30" step_id="6ad589ee-6735-4e9c-8e05-8a4c54748335" container_id="35" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="4614,525.999999999999,220,338" />
      <Node id="31" step_id="S9d0c6a31d29f4b41bd4130c1db52b90c" container_id="30" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="ReadRange" bounds="4620,549.999999999999,208,74" />
      <Node id="32" step_id="S6767dcb32faf40d1b5c0f2db6cbdb769" container_id="30" order="3" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="WriteRange" bounds="4620,783.999999999999,208,74" />
      <Node id="33" step_id="S592ce27c6a724646ab71fae606c68982" container_id="35" order="" type="EndLoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="4864,666.999999999998,76,56" />
      <Node id="34" step_id="S6a5e12b918e54ec0b9604805ef2f4a97" container_id="35" order="" type="EndSwitchCaseNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="4970,666.999999999999,56,56" />
      <Node id="35" step_id="" container_id="19" order="1" type="FlowControlGroupNode" invoke_type="" flowcontrol_type="SwitchCase" flowcontrol_enabled="True" expanded="" text="" desc="0" bounds="2217,288.499999999999,208,54" />
      <Node id="36" step_id="S8328e1a557444bee9d565a2325c17d86" container_id="38" order="" type="SwitchDefaultNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="2221,327.5,56,56" />
      <Node id="37" step_id="S02591937889a4e5aa1cbf73f86a615e8" container_id="38" order="" type="EndSwitchDefaultNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="2769,327.5,56,56" />
      <Node id="38" step_id="" container_id="19" order="2" type="FlowControlGroupNode" invoke_type="" flowcontrol_type="SwitchCase" flowcontrol_enabled="True" expanded="" text="" bounds="2217,342.5,208,54" />
      <Node id="39" step_id="Sc558f5e9de304e0594e7ad90cb0038ab" container_id="" order="" type="LoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="116,54,76,56" />
      <Node id="40" step_id="S956742ad9b3c4863bb520d24fa97a03f" container_id="" order="" type="EndLoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="900,266,76,56" />
      <Node id="41" step_id="S79063850a97846dcb1f78e91041a6642" container_id="" order="" type="DecisionThenNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="1078,266,76,56" />
      <Node id="42" step_id="S5fde29d2532f4acd80fda93e12cfd2d3" container_id="" order="" type="EndDecisionThenNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="1434,266,76,56" />
      <Node id="43" step_id="40a76244-8fe9-426a-9c0e-97eac392f8c4" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="1184,164,220,260" />
      <Node id="44" step_id="Scb9cfb5756ad4eb5aaaf9efb9eb944dd" container_id="43" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="CloseExcel" bounds="1190,188,208,74" />
      <Node id="45" step_id="S5890c4b49e0648d48877c27dea8a10b0" container_id="43" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="DeleteFile" bounds="1190,266,208,74" />
      <Node id="46" step_id="Sa664d94402db42a0a08c36db90ce3981" container_id="43" order="2" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="TerminateAll" bounds="1190,344,208,74" />
      <Node id="47" step_id="Seec20521216e495c86fa7f60a13ba3a9" container_id="22" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Assign" bounds="4620,627.999999999997,208,74" />
      <Node id="48" step_id="S08f5176498994de5b5f857dabfe6050e" container_id="30" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Assign" bounds="4620,627.999999999999,208,74" />
      <Node id="49" step_id="S1b2253407fba43ea8ff61840e41277b1" container_id="38" order="" type="LoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="2307,327.5,76,56" />
      <Node id="50" step_id="Sda5120e40f074c1fa37075c0cfa022cd" container_id="38" order="" type="EndLoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="2663,327.5,76,56" />
      <Node id="51" step_id="094e2ffc-93ff-4922-8fa3-7f86681e4c36" container_id="38" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="2413,186.5,220,338" />
      <Node id="52" step_id="S50c0ae8a94f04d438d2627bcf581e45b" container_id="51" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="ReadRange" bounds="2419,210.5,208,74" />
      <Node id="53" step_id="Se22b245446d646a3a699705792630136" container_id="51" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Assign" bounds="2419,288.5,208,74" />
      <Node id="54" step_id="Se2c93c70a4144358bb2182f78fce9b74" container_id="51" order="3" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="WriteRange" bounds="2419,444.5,208,74" />
      <Node id="55" step_id="S2c92d794d5f541499a3ac96c66920c02" container_id="22" order="2" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Assign" bounds="4620,705.999999999997,208,74" />
      <Node id="56" step_id="S304b00d630904cf3ba81927ee30a2522" container_id="30" order="2" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Assign" bounds="4620,705.999999999999,208,74" />
      <Node id="57" step_id="S328cdb2bc62e4c97ad912fc38afd9f65" container_id="51" order="2" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Assign" bounds="2419,366.5,208,74" />
      <Node id="58" step_id="Sfc6ef0b5be114e95b3f10c70cda6625e" container_id="12" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="GetSheetName" bounds="1717,266,208,74" />
      <Node id="59" step_id="Sf2320cc0df9341fb8d559083275da7cc" container_id="12" order="2" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="CopyWorkSheet" bounds="1717,344,208,74" />
    </Nodes>
    <Links>
      <Link id="60" color="#FF888888" origin_node_id="2" dest_node_id="4" text="" bounds="439,79,36,6" points="442,82;472,82" />
      <Link id="61" color="#FF888888" origin_node_id="4" dest_node_id="6" text="" bounds="689,79,36,6" points="692,82;722,82" />
      <Link id="62" color="#FF0DB2AD" origin_node_id="6" dest_node_id="7" text="TRUE" bounds="795,79,36,6" points="798,82;828,82" />
      <Link id="63" color="#FF0DB2AD" origin_node_id="6" dest_node_id="9" text="FALSE" bounds="757,107,6,162" points="760,110;760,266" />
      <Link id="64" color="#FF888888" origin_node_id="7" dest_node_id="9" text="" bounds="780.509433962264,131,116.830188679245,138" points="894.339622641509,134;783.509433962264,266" />
      <Link id="65" color="#FF0DB2AD" origin_node_id="10" dest_node_id="11" text="" bounds="1613,291,36,6" points="1616,294;1646,294" />
      <Link id="66" color="#FF888888" origin_node_id="11" dest_node_id="12" text="" bounds="1678,291,36,6" points="1681,294;1711,294" />
      <Link id="67" color="#FF888888" origin_node_id="17" dest_node_id="18" text="" bounds="2493,291,36,6" points="2496,294;2526,294" />
      <Link id="68" color="#FF888888" origin_node_id="18" dest_node_id="1" text="" bounds="2599,291,36,6" points="2602,294;2632,294" />
      <Link id="69" color="#FF6868E1" origin_node_id="21" dest_node_id="22" text="" bounds="4415,443.999999999999,214,6" points="4626,446.999999999999;4418,446.999999999999" />
      <Link id="70" color="#FF888888" origin_node_id="22" dest_node_id="25" text="" bounds="4415,443.999999999999,214,6" points="4626,446.999999999999;4418,446.999999999999" />
      <Link id="71" color="#FF888888" origin_node_id="25" dest_node_id="26" text="" bounds="4415,443.999999999999,214,6" points="4626,446.999999999999;4418,446.999999999999" />
      <Link id="72" color="#FF6868E1" origin_node_id="29" dest_node_id="30" text="" bounds="4415,497.999999999999,214,6" points="4626,500.999999999999;4418,500.999999999999" />
      <Link id="73" color="#FF888888" origin_node_id="30" dest_node_id="33" text="" bounds="4415,497.999999999999,214,6" points="4626,500.999999999999;4418,500.999999999999" />
      <Link id="74" color="#FF888888" origin_node_id="33" dest_node_id="34" text="" bounds="4415,497.999999999999,214,6" points="4626,500.999999999999;4418,500.999999999999" />
      <Link id="75" color="#FF888888" origin_node_id="0" dest_node_id="39" text="" bounds="83,79,36,6" points="86,82;116,82" />
      <Link id="76" color="#FF6868E1" origin_node_id="39" dest_node_id="2" text="" bounds="189,79,36,6" points="192,82;222,82" />
      <Link id="77" color="#FF888888" origin_node_id="9" dest_node_id="40" text="" bounds="795,291,108,6" points="798,294;900,294" />
      <Link id="78" color="#FF888888" origin_node_id="40" dest_node_id="41" text="" bounds="973,291,108,6" points="976,294;1078,294" />
      <Link id="79" color="#FF888888" origin_node_id="42" dest_node_id="10" text="" bounds="1507,291,36,6" points="1510,294;1540,294" />
      <Link id="80" color="#FF0DB2AD" origin_node_id="41" dest_node_id="43" text="" bounds="1151,291,36,6" points="1154,294;1184,294" />
      <Link id="81" color="#FF888888" origin_node_id="43" dest_node_id="42" text="" bounds="1401,291,36,6" points="1404,294;1434,294" />
      <Link id="82" color="#FF888888" origin_node_id="19" dest_node_id="17" text="" bounds="2428,291,36,6" points="2431,294;2461,294" />
      <Link id="83" color="#FF6868E1" origin_node_id="49" dest_node_id="51" text="" bounds="2208,164,56,6" points="2261,167;2211,167" />
      <Link id="84" color="#FF888888" origin_node_id="51" dest_node_id="50" text="" bounds="2208,164,56,6" points="2261,167;2211,167" />
      <Link id="85" color="#FF888888" origin_node_id="50" dest_node_id="37" text="" bounds="2208,164,56,6" points="2261,167;2211,167" />
      <Link id="86" color="#FF888888" origin_node_id="14" dest_node_id="19" text="" bounds="2178,291,36,6" points="2181,294;2211,294" />
      <Link id="87" color="#FF888888" origin_node_id="20" dest_node_id="21" text="" bounds="4415,443.999999999999,214,6" points="4626,446.999999999999;4418,446.999999999999" />
      <Link id="88" color="#FF888888" origin_node_id="28" dest_node_id="29" text="" bounds="4415,497.999999999999,214,6" points="4626,500.999999999999;4418,500.999999999999" />
      <Link id="89" color="#FF888888" origin_node_id="36" dest_node_id="49" text="" bounds="2208,164,56,6" points="2261,167;2211,167" />
      <Link id="90" color="#FF888888" origin_node_id="12" dest_node_id="14" text="" bounds="1928,291,36,6" points="1931,294;1961,294" />
    </Links>
  </Diagram>
</Process>