
<Process id="59f4d723-e962-411b-9cdb-f3e01307ef48" type="event" workType="foreground" name="E_Error" version="1.0" designerVersion="1.6.500.09031" isValid="true">
  <Properties>
    <Property key="Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="Os" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="Microsoft Windows 10 Pro64비트" />
    <Property key="Resolution" controlType="String" valueType="System.String" formatType="String_Size" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="1920x1080" />
    <Property key="RunningTime" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="7" />
    <Property key="Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="0" />
    <Property key="CreatedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2020-11-04 18:03:09" />
    <Property key="CreatedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastModifiedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2020-11-05 23:33:04" />
    <Property key="LastModifiedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" />
    <Property key="LastPublishedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" />
  </Properties>
  <LinkItems />
  <Variables>
    <Variable name="sender" scope="Input" valueType="Any" formatType="Any" initValue="this" desc="Task Object" />
    <Variable name="args" scope="Input" valueType="Any" formatType="Any" initValue="{message:'error message'}" desc="Exception Object" />
    <Variable name="senderName" scope="Normal" valueType="Any" formatType="Any" initValue="this.sender.constructor.name" desc="Task Name" />
    <Variable name="errorMessage" scope="Normal" valueType="Any" formatType="Any" initValue="Bot.GetProgressInfo(this.senderName) + '\n' + this.args.message" desc="Default Message Format" />
  </Variables>
  <Steps>
    <Step id="Sae7e544cac5f477c9b8ff2a5cf21310b" ver="200825001" createVer="200825001" type="Flow" name="Loop" apptitle="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="4b3fc773-3e78-4772-aae1-6c8ab11b0a01" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_InitializeIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.i = 0" />
        <Property type="Flow" key="Conditions_LoopCondition" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i &lt; this.sender.outTotalRow" />
        <Property type="Flow" key="Conditions_UpdateIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.i++" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S1afbd4d201d84f959bc01d1cfdd731ea" type="Flow" name="EndLoop" />
      </RelatedSteps>
      <Script><![CDATA[for (this.i = 0; this.i < this.sender.outTotalRow; this.i++) {]]></Script>
    </Step>
    <Step id="S9644f89a509c4614a8f1bbccac0952c1" ver="200825001" createVer="200825001" type="Desktop" name="MessageBox" apptitle="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="01ba8cee-a1f0-4012-ae8c-c9da0dc88f43" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Conditions_Arguments" controlType="Object" valueType="System.Object" formatType="Any" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'같은 시트가 존재합니다.\n1.종료 2.업데이트'" />
        <Property type="Desktop" key="Command_Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="4" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[MsgBox('같은 시트가 존재합니다.\n1.종료 2.업데이트', 4);]]></Script>
    </Step>
    <Step id="S5fe368969bc34aadae10a2c9f767460b" ver="200825001" createVer="200825001" type="Desktop" name="InputBox" apptitle="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="f27a20de-5719-4d19-a29d-80046a25a30b" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo" />
        <Property type="Desktop" key="Conditions_DefaultValue" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="''" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varChoiceOneTwo = InputBox('');]]></Script>
    </Step>
    <Step id="S0ee71425d3de4e36a8f591596e23b9f3" ver="200825001" createVer="200825001" type="Flow" name="Decision" apptitle="" tag="" depth="2" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="e5b6d27f-0467-4def-9834-5703f661a86d" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo== 1 || this.sender.varChoiceOneTwo ==2" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo== 1 || this.sender.varChoiceOneTwo ==2" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Saabc03784fae4807ac6c8de6ac7d8d27" type="Flow" name="Else" />
        <RelatedStep id="Sc2c462e67cb84684ba2fa0edc70677fa" type="Flow" name="EndDecision" />
      </RelatedSteps>
      <Script><![CDATA[if (this.sender.varChoiceOneTwo== 1 || this.sender.varChoiceOneTwo ==2) {]]></Script>
    </Step>
    <Step id="S3e3371607cf342f7815d2f498c9af1e7" ver="200825001" createVer="200825001" type="Flow" name="Break" apptitle="" tag="" depth="3" stmttype="Jump" enabled="True" mainSet="0">
      <Properties id="3dd8a9d7-be21-45c4-982b-f025a5e79c38" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[break;]]></Script>
    </Step>
    <Step id="Saabc03784fae4807ac6c8de6ac7d8d27" ver="200825001" createVer="200825001" type="Flow" name="Else" apptitle="" tag="" depth="3" stmttype="CloseOpenBlock" enabled="True" mainSet="0">
      <Properties id="d1c0228e-08fc-48a4-bd16-34a47b1760fc" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S0ee71425d3de4e36a8f591596e23b9f3" type="Flow" name="Decision" />
      </RelatedSteps>
      <Script><![CDATA[}else{]]></Script>
    </Step>
    <Step id="Sc2c462e67cb84684ba2fa0edc70677fa" ver="200825001" createVer="200825001" type="Flow" name="EndDecision" apptitle="" tag="" depth="3" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="a24917ef-05f5-40c8-b326-9b0f7dde2f76" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S0ee71425d3de4e36a8f591596e23b9f3" type="Flow" name="Decision" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S1afbd4d201d84f959bc01d1cfdd731ea" ver="200825001" createVer="200825001" type="Flow" name="EndLoop" apptitle="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="cbf4f606-9c0c-4a2f-9fda-0a8d33e9bffb" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sae7e544cac5f477c9b8ff2a5cf21310b" type="Flow" name="Loop" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S3fdd89796e7b449eafd21e4b76d14f44" ver="200825001" createVer="200825001" type="Flow" name="DecisionThen" apptitle="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="72cc983d-95ce-499e-bbe3-a388d40069d4" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo == 1" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo == 1" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Saab3aa1a824345e989d3461c769d00c0" type="Flow" name="EndDecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[if (this.sender.varChoiceOneTwo == 1) {]]></Script>
    </Step>
    <Step id="Sb66ef8703b2d4d1b875a2f53a5242335" ver="200825001" createVer="200825001" type="Excel" name="CloseExcel" apptitle="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="e5115fb6-feb0-4b2b-964e-61701e3f6f38" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="File_Force" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.CloseExcel(this.closeexcel_info_10);]]></Script>
    </Step>
    <Step id="S74554c67a0514c74a59d040291e1ccad" ver="200825001" createVer="200825001" type="Excel" name="CloseExcel" apptitle="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="e5115fb6-feb0-4b2b-964e-61701e3f6f38" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="File_Force" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.CloseExcel(this.closeexcel_info_11);]]></Script>
    </Step>
    <Step id="S310b27c48f764a678219710fdb5e5fc4" ver="200825001" createVer="200825001" type="Desktop" name="DeleteFile" apptitle="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="92c0c013-8ee6-481a-b3aa-c5591a4c62f6" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Command_Path" controlType="File" valueType="System.String" formatType="String_FilePath" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'C:\\Temp\\데이터excel.xls'" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[SystemLib.DeleteFile('C:\\Temp\\데이터excel.xls');]]></Script>
    </Step>
    <Step id="S1b9e9bcd31134e3a8c615ba132966f9c" ver="200825001" createVer="200825001" type="Flow" name="TerminateAll" apptitle="" tag="" depth="2" stmttype="Jump" enabled="True" mainSet="0">
      <Properties id="a2b013df-9dfd-4e59-b0de-931d95d988ec" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_ExitType" controlType="PropertyItemToggleExView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="Stop" toggle="Pass;Fail;Stop" order="1" />
        <Property type="Flow" key="Conditions_ExitCode" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Result" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Exit('Stop', null, null);]]></Script>
    </Step>
    <Step id="Saab3aa1a824345e989d3461c769d00c0" ver="200825001" createVer="200825001" type="Flow" name="EndDecisionThen" apptitle="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="43428b53-a45d-4436-9d35-3c76b66075cd" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S3fdd89796e7b449eafd21e4b76d14f44" type="Flow" name="DecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="Se1b588f2bc66455f9e487e5584d9b5c6" ver="200825001" createVer="200825001" type="Flow" name="DecisionThen" apptitle="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="72cc983d-95ce-499e-bbe3-a388d40069d4" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo == 2" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varChoiceOneTwo == 2" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S4fb2f2ae6ace472c81421615e546c80b" type="Flow" name="EndDecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[if (this.sender.varChoiceOneTwo == 2) {]]></Script>
    </Step>
    <Step id="S3d5c0b92b79247e1a1a8834f57e05746" ver="200825001" createVer="200825001" type="Flow" name="Block" apptitle="" tag="" depth="2" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="44739690-7ce3-4d76-9eef-8a425d9690c1" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Title" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="' 업데이트 입력'" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sa2785a31d51c4acb93fe93bddbc8c484" type="Flow" name="EndBlock" />
      </RelatedSteps>
      <Script><![CDATA[{]]></Script>
    </Step>
    <Step id="S4054ba557fa145428b8db42cae203af6" ver="200825001" createVer="200825001" type="Excel" name="DeleteWorkSheet" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="d6856038-89f2-4957-9885-03c64ee6e9b9" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSheetBoolean" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.DeleteWorkSheet(this.deleteworksheet_info_17);]]></Script>
    </Step>
    <Step id="S611c55d550af4fe5bc2095f370fbc093" ver="200825001" createVer="200825001" type="Excel" name="GetSheetName" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="53d87f2d-4c90-41ec-8399-72e04c3570c8" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="Output_SheetName" controlType="OutputControlType" valueType="System.String" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varTryExpBoolean" />
        <Property type="Excel" key="Sheet_Position" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="1" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varTryExpBoolean = Excel.GetSheetName(this.getsheetname_info_18);]]></Script>
    </Step>
    <Step id="S966ce1c799ae444abbd01ae30d373195" ver="200825001" createVer="200825001" type="Excel" name="CopyWorkSheet" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="ba16f69d-1a63-483b-82d5-7761fdb10d69" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="--Ignore--" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="File_SourceSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'draft'" />
        <Property type="Excel" key="File_TargetSheet" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftSheetName" />
        <Property type="Excel" key="File_BeforeSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varTryExpBoolean" />
        <Property type="Excel" key="File_AfterSheet" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[try{
    Excel.CopyWorkSheet(this.copyworksheet_info_19);
}catch(e){
    Warn('CatchException: ' + e.message);
}
]]></Script>
    </Step>
    <Step id="S39ec88569c194f82be06d71f599e7388" ver="200825001" createVer="200825001" type="Excel" name="CopyPaste" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="f56c084b-eb69-4f04-812b-06d8f26b7e44" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="File_SourceExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="File_SourceSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소(전체)'" />
        <Property type="Excel" key="File_SourceRange" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'A2:'+this.sender.varRowCount[0]" />
        <Property type="Excel" key="File_TargetExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="File_TargetSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftSheetName" />
        <Property type="Excel" key="File_TargetRange" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'A2:'+this.sender.varRowCount[0]" />
        <Property type="Excel" key="File_TargetAutoSave" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="All" valuelist="All;UsingSourceTheme;Formulas;ExceptBorders;Values;ColumnWidths;Formats;FormulasAndNumberFormats;Comments;ValuesAndNumberFormats;Validation;MergingConditionalFormats" />
        <Property type="Excel" key="Input_PasteOperation" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="None" valuelist="None;Add;Subtract;Multiply;Divide" />
        <Property type="Excel" key="Input_PasteSkipBlanks" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteTranspose" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteUseLink" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.CopyPaste(this.copypaste_info_20);]]></Script>
    </Step>
    <Step id="S7d9689afcaaa4c09ac2357b07c531225" ver="200825001" createVer="200825001" type="Excel" name="CopyPaste" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="f56c084b-eb69-4f04-812b-06d8f26b7e44" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="File_SourceExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="File_SourceSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소(전체)'" />
        <Property type="Excel" key="File_SourceRange" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'J2:'+this.sender.varRowCount[1]" />
        <Property type="Excel" key="File_TargetExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="File_TargetSheet" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftSheetName" />
        <Property type="Excel" key="File_TargetRange" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'H2:'+this.sender.varRowCount[2]" />
        <Property type="Excel" key="File_TargetAutoSave" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="All" valuelist="All;UsingSourceTheme;Formulas;ExceptBorders;Values;ColumnWidths;Formats;FormulasAndNumberFormats;Comments;ValuesAndNumberFormats;Validation;MergingConditionalFormats" />
        <Property type="Excel" key="Input_PasteOperation" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="None" valuelist="None;Add;Subtract;Multiply;Divide" />
        <Property type="Excel" key="Input_PasteSkipBlanks" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteTranspose" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
        <Property type="Excel" key="Input_PasteUseLink" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.CopyPaste(this.copypaste_info_21);]]></Script>
    </Step>
    <Step id="Sf947472a4c184930a6a7f6be67569e06" ver="200825001" createVer="200825001" type="Flow" name="Loop" apptitle="" tag="" depth="3" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="7d4d8164-4128-4f7a-8b5b-713d6d79691b" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_InitializeIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i = 2" />
        <Property type="Flow" key="Conditions_LoopCondition" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.i &lt;=this.sender.outTotalRow" />
        <Property type="Flow" key="Conditions_UpdateIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.i++" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sa637653fde3f41f5ab9cddf9a7f6148e" type="Flow" name="EndLoop" />
      </RelatedSteps>
      <Script><![CDATA[for (this.i = 2; this.i <=this.sender.outTotalRow; this.i++) {]]></Script>
    </Step>
    <Step id="S2ba417f8a20441c6be94f3f44228c831" ver="200825001" createVer="200825001" type="Excel" name="ReadRange" apptitle="" tag="" depth="4" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="48d3fd40-ddd4-442f-8dc8-9152e8776905" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="Output_DataArray" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varDayArray[0]" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소(전체)'" />
        <Property type="Excel" key="Sheet_Range" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'G'+this.i" />
        <Property type="Excel" key="Input_ReadCellType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="Data" valuelist="Data;Value;Formula;Text" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varDayArray[0] = Excel.ReadRange(this.readrange_info_23);]]></Script>
    </Step>
    <Step id="S5491378c9d804e8db722f2a33b8d3d84" ver="200825001" createVer="200825001" type="Excel" name="ReadRange" apptitle="" tag="" depth="4" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="48d3fd40-ddd4-442f-8dc8-9152e8776905" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="Output_DataArray" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varDayArray[1]" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소(전체)'" />
        <Property type="Excel" key="Sheet_Range" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'H'+this.i" />
        <Property type="Excel" key="Input_ReadCellType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="Data" valuelist="Data;Value;Formula;Text" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varDayArray[1] = Excel.ReadRange(this.readrange_info_24);]]></Script>
    </Step>
    <Step id="Sa58704bf14684efcb391178a2ab9b061" ver="200825001" createVer="200825001" type="Excel" name="ReadRange" apptitle="" tag="" depth="4" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="48d3fd40-ddd4-442f-8dc8-9152e8776905" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="Output_DataArray" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varDayArray[2]" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소(전체)'" />
        <Property type="Excel" key="Sheet_Range" controlType="String" valueType="System.String" formatType="String_ExcelRange" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'I'+this.i" />
        <Property type="Excel" key="Input_ReadCellType" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="Data" valuelist="Data;Value;Formula;Text" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varDayArray[2] = Excel.ReadRange(this.readrange_info_25);]]></Script>
    </Step>
    <Step id="S62971cab349e454680d4d6712c8b4cbf" ver="200825001" createVer="200825001" type="Flow" name="Assign" apptitle="" tag="" depth="4" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="97d60322-91c8-4b61-817c-b43b03bddb43" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varDayArray[4]" />
        <Property type="Flow" key="Conditions_Value" controlType="PropertyItemTextView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'평일 : '+this.sender.varDayArray[0]+'\n'+'토요일 : '+this.sender.varDayArray[1]+&#xD;&#xA;'\n'+'일요일/공휴일 : '+this.sender.varDayArray[2]&#xD;&#xA;" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.sender.varDayArray[4] = '평일 : '+this.sender.varDayArray[0]+'\n'+'토요일 : '+this.sender.varDayArray[1]+
'\n'+'일요일/공휴일 : '+this.sender.varDayArray[2]
;]]></Script>
    </Step>
    <Step id="S8974b27460bc4596b101c6909d71dcf1" ver="200825001" createVer="200825001" type="Excel" name="WriteRange" apptitle="" tag="" depth="4" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="daf21c32-048a-45c0-8c92-961f1ee32956" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftExcelHandle" />
        <Property type="Excel" key="Input_DataArray" controlType="Object[][]" valueType="System.Object[][]" formatType="Array2D" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varDayArray[4]" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.outDraftSheetName" />
        <Property type="Excel" key="Sheet_StartCell" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'G'+this.i" />
        <Property type="Excel" key="File_AutoSave" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.WriteRange(this.writerange_info_27);]]></Script>
    </Step>
    <Step id="Sa637653fde3f41f5ab9cddf9a7f6148e" ver="200825001" createVer="200825001" type="Flow" name="EndLoop" apptitle="" tag="" depth="4" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="4a9e4fdb-711d-4d72-b5e6-516ef2b26af1" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sf947472a4c184930a6a7f6be67569e06" type="Flow" name="Loop" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S7f42a79972174a8e94729172519568b0" ver="200825001" createVer="200825001" type="Excel" name="CloseExcel" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="ab1805e4-68c9-49ab-937e-1ca25b9295e0" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.sender.varSampleExcelHandel" />
        <Property type="Excel" key="File_Force" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Excel.CloseExcel(this.closeexcel_info_29);]]></Script>
    </Step>
    <Step id="Sf06d52277f3f484fa998423a562934eb" ver="200825001" createVer="200825001" type="Desktop" name="DeleteFile" apptitle="" tag="" depth="3" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="92c0c013-8ee6-481a-b3aa-c5591a4c62f6" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Command_Path" controlType="File" valueType="System.String" formatType="String_FilePath" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'C:\\Temp\\데이터excel.xls'" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[SystemLib.DeleteFile('C:\\Temp\\데이터excel.xls');]]></Script>
    </Step>
    <Step id="Sa2785a31d51c4acb93fe93bddbc8c484" ver="200825001" createVer="200825001" type="Flow" name="EndBlock" apptitle="" tag="" depth="3" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="3f829443-48cf-4095-86de-fcd99d8664c0" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S3d5c0b92b79247e1a1a8834f57e05746" type="Flow" name="Block" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S4fb2f2ae6ace472c81421615e546c80b" ver="200825001" createVer="200825001" type="Flow" name="EndDecisionThen" apptitle="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="43428b53-a45d-4436-9d35-3c76b66075cd" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Se1b588f2bc66455f9e487e5584d9b5c6" type="Flow" name="DecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
  </Steps>
  <JScript><![CDATA[function E_Error(args) {

    this.sender = (typeof args != 'undefined') ? args.sender : this;
    this.args = (typeof args != 'undefined') ? args.args : {message:'error message'};
    this.senderName = this.sender.constructor.name;
    this.errorMessage = Bot.GetProgressInfo(this.senderName) + '\n' + this.args.message;

    this.run = function() {

        //------------------------------------------------
        STEP('Sae7e544cac5f477c9b8ff2a5cf21310b', '[1] For');
        for (this.i = 0; this.i < this.sender.outTotalRow; this.i++) {

            //------------------------------------------------
            STEP('S9644f89a509c4614a8f1bbccac0952c1', '[2] MessageBox');
            MsgBox('같은 시트가 존재합니다.\n1.종료 2.업데이트', 4);

            //------------------------------------------------
            STEP('S5fe368969bc34aadae10a2c9f767460b', '[3] InputBox');
            this.sender.varChoiceOneTwo = InputBox('');

            //------------------------------------------------
            STEP('S0ee71425d3de4e36a8f591596e23b9f3', '[4] If');
            if (this.sender.varChoiceOneTwo== 1 || this.sender.varChoiceOneTwo ==2) {

                //------------------------------------------------
                STEP('S3e3371607cf342f7815d2f498c9af1e7', '[5] Break');
                break;

            //------------------------------------------------
            }else{
                STEP('Saabc03784fae4807ac6c8de6ac7d8d27', '[6] Else');

            //------------------------------------------------
            }
            STEP('Sc2c462e67cb84684ba2fa0edc70677fa', '[7] End-If');

        //------------------------------------------------
        }
        STEP('S1afbd4d201d84f959bc01d1cfdd731ea', '[8] End-For');

        //------------------------------------------------
        STEP('S3fdd89796e7b449eafd21e4b76d14f44', '[9] IfThen');
        if (this.sender.varChoiceOneTwo == 1) {

            //------------------------------------------------
            STEP('Sb66ef8703b2d4d1b875a2f53a5242335', '[10] CloseExcel');
            Excel.CloseExcel(this.closeexcel_info_10);

            //------------------------------------------------
            STEP('S74554c67a0514c74a59d040291e1ccad', '[11] CloseExcel');
            Excel.CloseExcel(this.closeexcel_info_11);

            //------------------------------------------------
            STEP('S310b27c48f764a678219710fdb5e5fc4', '[12] DeleteFile');
            SystemLib.DeleteFile('C:\\Temp\\데이터excel.xls');

            //------------------------------------------------
            STEP('S1b9e9bcd31134e3a8c615ba132966f9c', '[13] TerminateAll');
            Exit('Stop', null, null);

        //------------------------------------------------
        }
        STEP('Saab3aa1a824345e989d3461c769d00c0', '[14] End-IfThen');

        //------------------------------------------------
        STEP('Se1b588f2bc66455f9e487e5584d9b5c6', '[15] IfThen');
        if (this.sender.varChoiceOneTwo == 2) {

            //------------------------------------------------
            STEP('S3d5c0b92b79247e1a1a8834f57e05746', '[16] Block');
            {

                //------------------------------------------------
                STEP('S4054ba557fa145428b8db42cae203af6', '[17] DeleteWorkSheet');
                Excel.DeleteWorkSheet(this.deleteworksheet_info_17);

                //------------------------------------------------
                STEP('S611c55d550af4fe5bc2095f370fbc093', '[18] GetSheetName');
                this.sender.varTryExpBoolean = Excel.GetSheetName(this.getsheetname_info_18);

                //------------------------------------------------
                STEP('S966ce1c799ae444abbd01ae30d373195', '[19] CopyWorkSheet');
                try{
                    Excel.CopyWorkSheet(this.copyworksheet_info_19);
                }catch(e){
                    Warn('CatchException: ' + e.message);
                }


                //------------------------------------------------
                STEP('S39ec88569c194f82be06d71f599e7388', '[20] CopyPaste');
                Excel.CopyPaste(this.copypaste_info_20);

                //------------------------------------------------
                STEP('S7d9689afcaaa4c09ac2357b07c531225', '[21] CopyPaste');
                Excel.CopyPaste(this.copypaste_info_21);

                //------------------------------------------------
                STEP('Sf947472a4c184930a6a7f6be67569e06', '[22] For');
                for (this.i = 2; this.i <=this.sender.outTotalRow; this.i++) {

                    //------------------------------------------------
                    STEP('S2ba417f8a20441c6be94f3f44228c831', '[23] ReadRange');
                    this.sender.varDayArray[0] = Excel.ReadRange(this.readrange_info_23);

                    //------------------------------------------------
                    STEP('S5491378c9d804e8db722f2a33b8d3d84', '[24] ReadRange');
                    this.sender.varDayArray[1] = Excel.ReadRange(this.readrange_info_24);

                    //------------------------------------------------
                    STEP('Sa58704bf14684efcb391178a2ab9b061', '[25] ReadRange');
                    this.sender.varDayArray[2] = Excel.ReadRange(this.readrange_info_25);

                    //------------------------------------------------
                    STEP('S62971cab349e454680d4d6712c8b4cbf', '[26] Assign');
                    this.sender.varDayArray[4] = '평일 : '+this.sender.varDayArray[0]+'\n'+'토요일 : '+this.sender.varDayArray[1]+
                    '\n'+'일요일/공휴일 : '+this.sender.varDayArray[2]
                    ;

                    //------------------------------------------------
                    STEP('S8974b27460bc4596b101c6909d71dcf1', '[27] WriteRange');
                    Excel.WriteRange(this.writerange_info_27);

                //------------------------------------------------
                }
                STEP('Sa637653fde3f41f5ab9cddf9a7f6148e', '[28] End-For');

                //------------------------------------------------
                STEP('S7f42a79972174a8e94729172519568b0', '[29] CloseExcel');
                Excel.CloseExcel(this.closeexcel_info_29);

                //------------------------------------------------
                STEP('Sf06d52277f3f484fa998423a562934eb', '[30] DeleteFile');
                SystemLib.DeleteFile('C:\\Temp\\데이터excel.xls');

            //------------------------------------------------
            }
            STEP('Sa2785a31d51c4acb93fe93bddbc8c484', '[31] End-Block');

        //------------------------------------------------
        }
        STEP('S4fb2f2ae6ace472c81421615e546c80b', '[32] End-IfThen');


    }

    this.execute = function() {
        var result = null;
        result = this.run()
        if (result != null)
            return result;
    }
}
]]></JScript>
  <Diagram version="1.200" layout="Horizontal" nodesize="Normal">
    <Nodes>
      <Node id="0" step_id="" container_id="" order="" type="StartNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="START" bounds="30,54,56,56" />
      <Node id="1" step_id="" container_id="" order="" type="EndNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="END" bounds="4344,305,56,56" />
      <Node id="2" step_id="Sae7e544cac5f477c9b8ff2a5cf21310b" container_id="" order="" type="LoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="116,54,76,56" />
      <Node id="3" step_id="42449250-4150-4fa2-be75-be6f71211574" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="222,30,220,104" />
      <Node id="4" step_id="S9644f89a509c4614a8f1bbccac0952c1" container_id="3" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="MessageBox" bounds="228,54,208,74" />
      <Node id="5" step_id="363abe8e-03d5-4d8e-946e-183327f910f3" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="472,30,220,104" />
      <Node id="6" step_id="S5fe368969bc34aadae10a2c9f767460b" container_id="5" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="InputBox" bounds="478,54,208,74" />
      <Node id="7" step_id="S0ee71425d3de4e36a8f591596e23b9f3" container_id="" order="" type="DecisionNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="722,54,76,56" />
      <Node id="8" step_id="bd84dbf9-6942-4a00-9cc1-9a3629696c64" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="828,30,220,104" />
      <Node id="9" step_id="S3e3371607cf342f7815d2f498c9af1e7" container_id="8" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Break" bounds="834,54,208,74" />
      <Node id="10" step_id="Sc2c462e67cb84684ba2fa0edc70677fa" container_id="" order="" type="EndDecisionNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="722,305,76,56" />
      <Node id="11" step_id="S1afbd4d201d84f959bc01d1cfdd731ea" container_id="" order="" type="EndLoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="900,305,76,56" />
      <Node id="12" step_id="Se1b588f2bc66455f9e487e5584d9b5c6" container_id="" order="" type="DecisionThenNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="2040,305,76,56" />
      <Node id="13" step_id="S3d5c0b92b79247e1a1a8834f57e05746" container_id="" order="" type="BlockNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="2146,296.5,35,73" />
      <Node id="14" step_id="5c6c2f28-b6c2-4dbd-a3e8-5813fed75e66" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="2211,281,220,104" />
      <Node id="15" step_id="S4054ba557fa145428b8db42cae203af6" container_id="14" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="DeleteWorkSheet" bounds="2217,305,208,74" />
      <Node id="16" step_id="48171c21-1499-4613-af7e-2aa4e043d146" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="2461,281,220,104" />
      <Node id="17" step_id="S611c55d550af4fe5bc2095f370fbc093" container_id="16" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="GetSheetName" bounds="2467,305,208,74" />
      <Node id="18" step_id="b28c8ae9-df17-4a84-8bd9-91946d06f4b4" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="2711,281,220,104" />
      <Node id="19" step_id="S966ce1c799ae444abbd01ae30d373195" container_id="18" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="CopyWorkSheet" bounds="2717,305,208,74" />
      <Node id="20" step_id="874b24fc-134f-4844-ae9d-257bf19a7b91" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="2961,242,220,182" />
      <Node id="21" step_id="S39ec88569c194f82be06d71f599e7388" container_id="20" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="CopyPaste" bounds="2967,266,208,74" />
      <Node id="22" step_id="S7d9689afcaaa4c09ac2357b07c531225" container_id="20" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="CopyPaste" bounds="2967,344,208,74" />
      <Node id="23" step_id="Sf947472a4c184930a6a7f6be67569e06" container_id="" order="" type="LoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="3211,305,76,56" />
      <Node id="24" step_id="cd6bb99c-118f-4792-8715-b887854c7885" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="3317,164,220,338" />
      <Node id="25" step_id="S2ba417f8a20441c6be94f3f44228c831" container_id="24" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="ReadRange" bounds="3323,188,208,74" />
      <Node id="26" step_id="S5491378c9d804e8db722f2a33b8d3d84" container_id="24" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="ReadRange" bounds="3323,266,208,74" />
      <Node id="27" step_id="Sa58704bf14684efcb391178a2ab9b061" container_id="24" order="2" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="ReadRange" bounds="3323,344,208,74" />
      <Node id="28" step_id="S62971cab349e454680d4d6712c8b4cbf" container_id="24" order="3" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Assign" bounds="3323,422,208,74" />
      <Node id="29" step_id="c34efbde-7001-4425-bfa9-b17fec728564" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="3567,281,220,104" />
      <Node id="30" step_id="S8974b27460bc4596b101c6909d71dcf1" container_id="29" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="WriteRange" bounds="3573,305,208,74" />
      <Node id="31" step_id="Sa637653fde3f41f5ab9cddf9a7f6148e" container_id="" order="" type="EndLoopNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="3817,305,76,56" />
      <Node id="32" step_id="6fc52143-dfd0-4434-9689-31f2c5f94e2b" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="3923,242,220,182" />
      <Node id="33" step_id="S7f42a79972174a8e94729172519568b0" container_id="32" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="CloseExcel" bounds="3929,266,208,74" />
      <Node id="34" step_id="Sa2785a31d51c4acb93fe93bddbc8c484" container_id="" order="" type="EndBlockNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="4173,296.5,35,73" />
      <Node id="35" step_id="S4fb2f2ae6ace472c81421615e546c80b" container_id="" order="" type="EndDecisionThenNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="4238,305,76,56" />
      <Node id="36" step_id="S3fdd89796e7b449eafd21e4b76d14f44" container_id="" order="" type="DecisionThenNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="1078,305,76,56" />
      <Node id="37" step_id="Saab3aa1a824345e989d3461c769d00c0" container_id="" order="" type="EndDecisionThenNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="" bounds="1934,305,76,56" />
      <Node id="38" step_id="460771b3-32fb-4f4d-9d6b-4dd0761e584d" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="1684,281,220,104" />
      <Node id="39" step_id="S1b9e9bcd31134e3a8c615ba132966f9c" container_id="38" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="TerminateAll" bounds="1690,305,208,74" />
      <Node id="40" step_id="f18282ad-ba4c-4a69-8eb5-2476777d3985" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="1184,242,220,182" />
      <Node id="41" step_id="Sb66ef8703b2d4d1b875a2f53a5242335" container_id="40" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="CloseExcel" bounds="1190,266,208,74" />
      <Node id="42" step_id="e6a6eeb5-fccf-4a67-bcfc-0b8cd242393e" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="1434,281,220,104" />
      <Node id="43" step_id="S310b27c48f764a678219710fdb5e5fc4" container_id="42" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="DeleteFile" bounds="1440,305,208,74" />
      <Node id="44" step_id="S74554c67a0514c74a59d040291e1ccad" container_id="40" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="CloseExcel" bounds="1190,344,208,74" />
      <Node id="45" step_id="Sf06d52277f3f484fa998423a562934eb" container_id="32" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="DeleteFile" bounds="3929,344,208,74" />
    </Nodes>
    <Links>
      <Link id="46" color="#FF6868E1" origin_node_id="2" dest_node_id="3" text="" bounds="189,79,36,6" points="192,82;222,82" />
      <Link id="47" color="#FF888888" origin_node_id="3" dest_node_id="5" text="" bounds="439,79,36,6" points="442,82;472,82" />
      <Link id="48" color="#FF888888" origin_node_id="5" dest_node_id="7" text="" bounds="689,79,36,6" points="692,82;722,82" />
      <Link id="49" color="#FF0DB2AD" origin_node_id="7" dest_node_id="8" text="TRUE" bounds="795,79,36,6" points="798,82;828,82" />
      <Link id="50" color="#FF0DB2AD" origin_node_id="7" dest_node_id="10" text="FALSE" bounds="757,107,6,201" points="760,110;760,305" />
      <Link id="51" color="#FF888888" origin_node_id="8" dest_node_id="10" text="" bounds="776.856573705179,131,127.266932270916,177" points="901.123505976096,134;779.856573705179,305" />
      <Link id="52" color="#FF888888" origin_node_id="10" dest_node_id="11" text="" bounds="795,330,108,6" points="798,333;900,333" />
      <Link id="53" color="#FF0DB2AD" origin_node_id="12" dest_node_id="13" text="" bounds="2113,330,36,6" points="2116,333;2146,333" />
      <Link id="54" color="#FF888888" origin_node_id="13" dest_node_id="14" text="" bounds="2178,330,36,6" points="2181,333;2211,333" />
      <Link id="55" color="#FF888888" origin_node_id="14" dest_node_id="16" text="" bounds="2428,330,36,6" points="2431,333;2461,333" />
      <Link id="56" color="#FF888888" origin_node_id="16" dest_node_id="18" text="" bounds="2678,330,36,6" points="2681,333;2711,333" />
      <Link id="57" color="#FF888888" origin_node_id="18" dest_node_id="20" text="" bounds="2928,330,36,6" points="2931,333;2961,333" />
      <Link id="58" color="#FF888888" origin_node_id="20" dest_node_id="23" text="" bounds="3178,330,36,6" points="3181,333;3211,333" />
      <Link id="59" color="#FF6868E1" origin_node_id="23" dest_node_id="24" text="" bounds="3284,330,36,6" points="3287,333;3317,333" />
      <Link id="60" color="#FF888888" origin_node_id="24" dest_node_id="29" text="" bounds="3534,330,36,6" points="3537,333;3567,333" />
      <Link id="61" color="#FF888888" origin_node_id="29" dest_node_id="31" text="" bounds="3784,330,36,6" points="3787,333;3817,333" />
      <Link id="62" color="#FF888888" origin_node_id="31" dest_node_id="32" text="" bounds="3890,330,36,6" points="3893,333;3923,333" />
      <Link id="63" color="#FF888888" origin_node_id="32" dest_node_id="34" text="" bounds="4140,330,36,6" points="4143,333;4173,333" />
      <Link id="64" color="#FF888888" origin_node_id="34" dest_node_id="35" text="" bounds="4205,330,36,6" points="4208,333;4238,333" />
      <Link id="65" color="#FF888888" origin_node_id="0" dest_node_id="2" text="" bounds="83,79,36,6" points="86,82;116,82" />
      <Link id="66" color="#FF888888" origin_node_id="35" dest_node_id="1" text="" bounds="4311,330,36,6" points="4314,333;4344,333" />
      <Link id="67" color="#FF888888" origin_node_id="11" dest_node_id="36" text="" bounds="973,330,108,6" points="976,333;1078,333" />
      <Link id="68" color="#FF888888" origin_node_id="37" dest_node_id="12" text="" bounds="2007,330,36,6" points="2010,333;2040,333" />
      <Link id="69" color="#FF888888" origin_node_id="38" dest_node_id="37" text="" bounds="1901,330,36,6" points="1904,333;1934,333" />
      <Link id="70" color="#FF0DB2AD" origin_node_id="36" dest_node_id="40" text="" bounds="1151,330,36,6" points="1154,333;1184,333" />
      <Link id="71" color="#FF888888" origin_node_id="42" dest_node_id="38" text="" bounds="1651,330,36,6" points="1654,333;1684,333" />
      <Link id="72" color="#FF888888" origin_node_id="40" dest_node_id="42" text="" bounds="1401,330,36,6" points="1404,333;1434,333" />
    </Links>
  </Diagram>
</Process>