
<Process id="b27951c6-fda6-4dce-87d7-da9918e8034f" type="process" workType="foreground" name="P_CovidClinics" version="1.0" designerVersion="1.6.500.09031" readonly="false" isValid="true">
  <Properties>
    <Property key="Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onBefore" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onAfter" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="Os" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="Microsoft Windows 10 Pro64비트" />
    <Property key="Resolution" controlType="String" valueType="System.String" formatType="String_Size" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="1920x1080" />
    <Property key="RunningTime" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="964" />
    <Property key="Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="0" />
    <Property key="CreatedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2020-11-06 08:37:11" />
    <Property key="CreatedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastModifiedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2020-11-09 09:19:17" />
    <Property key="LastModifiedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
  </Properties>
  <LinkItems />
  <Variables>
    <Variable name="varDraftExcelHandle" scope="Normal" valueType="Any" formatType="Any" initValue="" desc="" />
    <Variable name="varDraftSheetName" scope="Normal" valueType="Any" formatType="Any" initValue="" desc="" />
    <Variable name="varTotalRow" scope="Normal" valueType="Any" formatType="Any" initValue="" desc="" />
  </Variables>
  <Steps>
    <Step id="S0acdb69b8d9d447585ce06024f4f6087" ver="200825001" createVer="200825001" type="Flow" name="RunTask" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="4998fe69-9d56-4fb9-94e4-669e74db067d" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_FillDraftExcel" />
        <Property type="Flow" key="Output_outDraftExcelHandle" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varDraftExcelHandle" />
        <Property type="Flow" key="Output_outTotalRow" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varTotalRow" />
        <Property type="Flow" key="Output_outDraftSheetName" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varDraftSheetName" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_FillDraftExcel', null);]]></Script>
    </Step>
    <Step id="S1542bcd41fd944d7b8633de1150d441a" ver="200825001" createVer="200825001" type="Flow" name="RunTask" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="b0096f76-2f59-4f6b-a1c0-990be3f6b548" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_AirPollutionLevel" />
        <Property type="Flow" key="Input_inDraftSheetName" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varDraftSheetName" />
        <Property type="Flow" key="Input_inDraftExcelHandle" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varDraftExcelHandle" />
        <Property type="Flow" key="Input_inTotalRow" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varTotalRow" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_AirPollutionLevel', {'inDraftSheetName':this.varDraftSheetName, 'inDraftExcelHandle':this.varDraftExcelHandle, 'inTotalRow':this.varTotalRow});]]></Script>
    </Step>
    <Step id="Saca7579cd68b4065ae83816709a1818e" ver="200825001" createVer="200825001" type="Flow" name="RunTask" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="014b2d18-75b1-429f-9e0b-6759c7c187a4" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_MoveToDB" />
        <Property type="Flow" key="Input_inDraftExcelHandle" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.varDraftExcelHandle" />
        <Property type="Flow" key="Input_inTotalRow" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varTotalRow" order="2" />
        <Property type="Flow" key="Input_inDraftSheetName" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varDraftSheetName" order="1" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_MoveToDB', {'inDraftExcelHandle':this.varDraftExcelHandle, 'inTotalRow':this.varTotalRow, 'inDraftSheetName':this.varDraftSheetName});]]></Script>
    </Step>
  </Steps>
  <JScript><![CDATA[function P_CovidClinics() {

    this.varDraftExcelHandle;
    this.varDraftSheetName;
    this.varTotalRow;

    this.run = function() {

        //------------------------------------------------
        STEP('S0acdb69b8d9d447585ce06024f4f6087', '[1] RunTask');
        RunTask(this, 'T_FillDraftExcel', null);

        //------------------------------------------------
        STEP('S1542bcd41fd944d7b8633de1150d441a', '[2] RunTask');
        RunTask(this, 'T_AirPollutionLevel', {'inDraftSheetName':this.varDraftSheetName, 'inDraftExcelHandle':this.varDraftExcelHandle, 'inTotalRow':this.varTotalRow});

        //------------------------------------------------
        STEP('Saca7579cd68b4065ae83816709a1818e', '[3] RunTask');
        RunTask(this, 'T_MoveToDB', {'inDraftExcelHandle':this.varDraftExcelHandle, 'inTotalRow':this.varTotalRow, 'inDraftSheetName':this.varDraftSheetName});


    }

    this.execute = function() {
        var result = null;
        result = this.run()
        if (result != null)
            return result;
    }
}
]]></JScript>
  <Diagram version="1.200" layout="Horizontal" nodesize="Normal">
    <Nodes>
      <Node id="0" step_id="" container_id="" order="" type="StartNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="START" bounds="30,58,56,56" />
      <Node id="1" step_id="" container_id="" order="" type="EndNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="END" bounds="776,58,56,56" />
      <Node id="2" step_id="Saca7579cd68b4065ae83816709a1818e" container_id="" order="" type="InvokeNode" invoke_type="Task" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="T_MoveToDB" bounds="556,30,190,112" />
      <Node id="4" step_id="S1542bcd41fd944d7b8633de1150d441a" container_id="" order="" type="InvokeNode" invoke_type="Task" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="T_AirPollutionLevel" bounds="336,30,190,112" />
      <Node id="6" step_id="S0acdb69b8d9d447585ce06024f4f6087" container_id="" order="" type="InvokeNode" invoke_type="Task" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="T_FillDraftExcel" bounds="116,30,190,112" />
    </Nodes>
    <Links>
      <Link id="3" color="#FF888888" origin_node_id="2" dest_node_id="1" text="" bounds="743,83,36,6" points="746,86;776,86" />
      <Link id="5" color="#FF888888" origin_node_id="4" dest_node_id="2" text="" bounds="523,83,36,6" points="526,86;556,86" />
      <Link id="7" color="#FF888888" origin_node_id="0" dest_node_id="6" text="" bounds="83,83,36,6" points="86,86;116,86" />
      <Link id="8" color="#FF888888" origin_node_id="6" dest_node_id="4" text="" bounds="303,83,36,6" points="306,86;336,86" />
    </Links>
  </Diagram>
</Process>