
<Process id="0323a907-69bd-4843-bb24-3d87d5980d2d" type="task" workType="foreground" name="T_S_Date" version="1.0" designerVersion="1.6.500.09031" isValid="true">
  <Properties>
    <Property key="Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onBefore" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onAfter" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="Os" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="Microsoft Windows 10 Pro64비트" />
    <Property key="Resolution" controlType="String" valueType="System.String" formatType="String_Size" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="1920x1080" />
    <Property key="RunningTime" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="12" />
    <Property key="Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="0" />
    <Property key="CreatedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2020-11-03 09:43:55" />
    <Property key="CreatedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastModifiedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2020-11-05 14:58:33" />
    <Property key="LastModifiedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" />
    <Property key="LastPublishedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" />
  </Properties>
  <LinkItems />
  <Variables>
    <Variable name="varNowDate" scope="Normal" valueType="Any" formatType="Any" initValue="" desc="" />
    <Variable name="outDayMonth" scope="Normal" valueType="Any" formatType="Any" initValue="[]" desc="" />
    <Variable name="outDraftSheetName" scope="Output" valueType="Any" formatType="Any" initValue="" desc="" />
    <Variable name="varZeroPlusDay" scope="Normal" valueType="Any" formatType="Any" initValue="" desc="" />
    <Variable name="varZeroPlusMonth" scope="Normal" valueType="Any" formatType="Any" initValue="" desc="" />
  </Variables>
  <Steps>
    <Step id="S8cbb1f345d974e4db433a00994af9e6a" ver="200825001" createVer="200825001" type="Flow" name="CustomLibrary" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="f4c29461-23ac-4609-a1d3-612b96351a87" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_LibraryScope" controlType="String" valueType="System.String" formatType="String" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="Project" />
        <Property type="Flow" key="Conditions_LibraryNamespace" controlType="String" valueType="System.String" formatType="String" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="JavaScript" />
        <Property type="Flow" key="Conditions_LibraryName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="DATE_Now" />
        <Property type="Flow" key="Conditions_LibraryType" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="JavaScript" />
        <Property type="Flow" key="Conditions_Result" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varNowDate" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.varNowDate = Script.JavaScript.DATE_Now();]]></Script>
    </Step>
    <Step id="Sf22f5923bb5b46f2bf6c8169d55ab307" ver="200825001" createVer="200825001" type="Flow" name="CustomLibrary" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="92c703d8-b91f-4911-ae04-eac2116df139" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_LibraryScope" controlType="String" valueType="System.String" formatType="String" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="Project" />
        <Property type="Flow" key="Conditions_LibraryNamespace" controlType="String" valueType="System.String" formatType="String" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="JavaScript" />
        <Property type="Flow" key="Conditions_LibraryName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="DATE_GetDate" />
        <Property type="Flow" key="Conditions_LibraryType" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="JavaScript" />
        <Property type="Flow" key="Conditions_Result" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.outDayMonth[0]" />
        <Property type="Flow" key="Arguments_date" controlType="String" valueType="System.String" formatType="String_DateTime" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varNowDate" order="1" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.outDayMonth[0] = Script.JavaScript.DATE_GetDate(this.varNowDate);]]></Script>
    </Step>
    <Step id="S3e36edd3ca254624b49def2c83aacd72" ver="200825001" createVer="200825001" type="Flow" name="CustomLibrary" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="bc61ff28-769d-4099-9308-9c7ce0c82d21" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_LibraryScope" controlType="String" valueType="System.String" formatType="String" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="Project" />
        <Property type="Flow" key="Conditions_LibraryNamespace" controlType="String" valueType="System.String" formatType="String" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="JavaScript" />
        <Property type="Flow" key="Conditions_LibraryName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="DATE_GetMonth" />
        <Property type="Flow" key="Conditions_LibraryType" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="JavaScript" />
        <Property type="Flow" key="Conditions_Result" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.outDayMonth[1]" />
        <Property type="Flow" key="Arguments_date" controlType="String" valueType="System.String" formatType="String_DateTime" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varNowDate" order="1" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.outDayMonth[1] = Script.JavaScript.DATE_GetMonth(this.varNowDate);]]></Script>
    </Step>
    <Step id="Sc5afe47931f04421bc1b43d36353dc90" ver="200825001" createVer="200825001" type="Flow" name="Assign" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="6a9553dd-5be7-4bc4-ae70-875a0a8cb638" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.outDayMonth[1]" />
        <Property type="Flow" key="Conditions_Value" controlType="PropertyItemTextView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.outDayMonth[1]+1" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.outDayMonth[1] = this.outDayMonth[1]+1;]]></Script>
    </Step>
    <Step id="Sb1f08fa9a75846d1863ecc21d72e8cb4" ver="200825001" createVer="200825001" type="Flow" name="RunTask" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="cd2490f5-9b73-434a-ad81-47c9e3d265de" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="Y" value="T_S_PlusZero" />
        <Property type="Flow" key="Input_inInt" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.outDayMonth[1]" />
        <Property type="Flow" key="Output_outStr" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varZeroPlusMonth" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_S_PlusZero', {'inInt':this.outDayMonth[1]});]]></Script>
    </Step>
    <Step id="S3039395a0e8a4d90bfed66c845471952" ver="200825001" createVer="200825001" type="Flow" name="RunTask" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="cd2490f5-9b73-434a-ad81-47c9e3d265de" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="Y" value="T_S_PlusZero" />
        <Property type="Flow" key="Input_inInt" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.outDayMonth[0]" />
        <Property type="Flow" key="Output_outStr" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.varZeroPlusDay" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_S_PlusZero', {'inInt':this.outDayMonth[0]});]]></Script>
    </Step>
    <Step id="Sc1437d3b66374af7a6c1247fc0ae3d59" ver="200825001" createVer="200825001" type="Flow" name="Assign" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="6a9553dd-5be7-4bc4-ae70-875a0a8cb638" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.outDayMonth[2]" />
        <Property type="Flow" key="Conditions_Value" controlType="PropertyItemTextView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="'선별진료소'+'('+this.varZeroPlusMonth+'.'+this.varZeroPlusDay+'.'+')'" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.outDayMonth[2] = '선별진료소'+'('+this.varZeroPlusMonth+'.'+this.varZeroPlusDay+'.'+')';]]></Script>
    </Step>
    <Step id="S298f29bb088b41dabf209bb4b03ea124" ver="200825001" createVer="200825001" type="Flow" name="Assign" apptitle="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="374984e1-ce7a-401b-888a-2f35a3a140d9" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Variable" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="False" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.outDraftSheetName" />
        <Property type="Flow" key="Conditions_Value" controlType="PropertyItemTextView" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="Y" value="this.outDayMonth[2]" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.outDraftSheetName = this.outDayMonth[2];]]></Script>
    </Step>
  </Steps>
  <JScript><![CDATA[function T_S_Date() {

    this.varNowDate;
    this.outDayMonth = [];
    this.outDraftSheetName;
    this.varZeroPlusDay;
    this.varZeroPlusMonth;

    this.run = function() {

        //------------------------------------------------
        STEP('S8cbb1f345d974e4db433a00994af9e6a', '[1] CustomLibrary');
        this.varNowDate = Script.JavaScript.DATE_Now();

        //------------------------------------------------
        STEP('Sf22f5923bb5b46f2bf6c8169d55ab307', '[2] CustomLibrary');
        this.outDayMonth[0] = Script.JavaScript.DATE_GetDate(this.varNowDate);

        //------------------------------------------------
        STEP('S3e36edd3ca254624b49def2c83aacd72', '[3] CustomLibrary');
        this.outDayMonth[1] = Script.JavaScript.DATE_GetMonth(this.varNowDate);

        //------------------------------------------------
        STEP('Sc5afe47931f04421bc1b43d36353dc90', '[4] Assign');
        this.outDayMonth[1] = this.outDayMonth[1]+1;

        //------------------------------------------------
        STEP('Sb1f08fa9a75846d1863ecc21d72e8cb4', '[5] RunTask');
        RunTask(this, 'T_S_PlusZero', {'inInt':this.outDayMonth[1]});

        //------------------------------------------------
        STEP('S3039395a0e8a4d90bfed66c845471952', '[6] RunTask');
        RunTask(this, 'T_S_PlusZero', {'inInt':this.outDayMonth[0]});

        //------------------------------------------------
        STEP('Sc1437d3b66374af7a6c1247fc0ae3d59', '[7] Assign');
        this.outDayMonth[2] = '선별진료소'+'('+this.varZeroPlusMonth+'.'+this.varZeroPlusDay+'.'+')';

        //------------------------------------------------
        STEP('S298f29bb088b41dabf209bb4b03ea124', '[8] Assign');
        this.outDraftSheetName = this.outDayMonth[2];


    }

    this.execute = function() {
        var result = null;
        result = this.run()
        if (result != null)
            return result;
        return {'outDraftSheetName':this.outDraftSheetName};
    }
}
]]></JScript>
  <Diagram version="1.200" layout="Horizontal" nodesize="Normal">
    <Nodes>
      <Node id="0" step_id="" container_id="" order="" type="StartNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="START" bounds="30,171,56,56" />
      <Node id="1" step_id="" container_id="" order="" type="EndNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="END" bounds="1056,171,56,56" />
      <Node id="2" step_id="S8cbb1f345d974e4db433a00994af9e6a" container_id="3" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="DATE_Now" bounds="122,54,208,74" />
      <Node id="3" step_id="1aaa4f96-1269-4acf-aebb-13c98a544691" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="116,30,220,338" />
      <Node id="4" step_id="Sf22f5923bb5b46f2bf6c8169d55ab307" container_id="3" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="DATE_GetDate" bounds="122,132,208,74" />
      <Node id="5" step_id="S3e36edd3ca254624b49def2c83aacd72" container_id="3" order="2" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="DATE_GetMonth" bounds="122,210,208,74" />
      <Node id="6" step_id="Sc5afe47931f04421bc1b43d36353dc90" container_id="3" order="3" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Assign" bounds="122,288,208,74" />
      <Node id="7" step_id="4616ad62-dcbb-4948-be96-c01f1493af6a" container_id="" order="" type="GroupNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="True" text="Untitled" bounds="806,108,220,182" />
      <Node id="8" step_id="Sc1437d3b66374af7a6c1247fc0ae3d59" container_id="7" order="0" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Assign" bounds="812,132,208,74" />
      <Node id="9" step_id="S298f29bb088b41dabf209bb4b03ea124" container_id="7" order="1" type="ActivityNode" invoke_type="" flowcontrol_type="" flowcontrol_enabled="" expanded="TRUE" text="Assign" bounds="812,210,208,74" />
      <Node id="10" step_id="Sb1f08fa9a75846d1863ecc21d72e8cb4" container_id="" order="" type="InvokeNode" invoke_type="Task" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="T_S_PlusZero" bounds="366,143,190,112" />
      <Node id="11" step_id="S3039395a0e8a4d90bfed66c845471952" container_id="" order="" type="InvokeNode" invoke_type="Task" flowcontrol_type="" flowcontrol_enabled="" expanded="" text="T_S_PlusZero" bounds="586,143,190,112" />
    </Nodes>
    <Links>
      <Link id="12" color="#FF888888" origin_node_id="0" dest_node_id="3" text="" bounds="83,196,36,6" points="86,199;116,199" />
      <Link id="13" color="#FF888888" origin_node_id="3" dest_node_id="10" text="" bounds="333,196,36,6" points="336,199;366,199" />
      <Link id="14" color="#FF888888" origin_node_id="10" dest_node_id="11" text="" bounds="553,196,36,6" points="556,199;586,199" />
      <Link id="15" color="#FF888888" origin_node_id="11" dest_node_id="7" text="" bounds="773,196,36,6" points="776,199;806,199" />
      <Link id="16" color="#FF888888" origin_node_id="7" dest_node_id="1" text="" bounds="1023,196,36,6" points="1026,199;1056,199" />
    </Links>
  </Diagram>
</Process>